return {
  {
    file="data/entities/animals/acidshooter.xml",
    herd="slimes",
    name="$animal_acidshooter",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/acidshooter_weak.xml",
    herd="slimes",
    name="$animal_acidshooter",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/alchemist.xml",
    herd="orcs",
    name="$animal_alchemist",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/ant.xml",
    herd="ant",
    name="$animal_ant",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/apparition/playerghost.xml",
    herd="apparition",
    name="$animal_playerghost",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying,glue_NOT"
  },
  {
    file="data/entities/animals/assassin.xml",
    herd="robot",
    name="$animal_assassin",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,robot"
  },
  {
    file="data/entities/animals/barfer.xml",
    herd="mage",
    name="$animal_barfer",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/basebot_hidden.xml",
    herd="robot",
    name="$animal_hidden",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,robot"
  },
  {
    file="data/entities/animals/basebot_neutralizer.xml",
    herd="robot",
    name="$animal_neutralizer",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,robot"
  },
  {
    file="data/entities/animals/basebot_sentry.xml",
    herd="robot",
    name="$animal_sentry",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,robot"
  },
  {
    file="data/entities/animals/basebot_soldier.xml",
    herd="robot",
    name="$animal_soldier",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,robot"
  },
  {
    file="data/entities/animals/bat.xml",
    herd="bat",
    name="$animal_bat",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/berserkspirit.xml",
    herd="ghost",
    name="$animal_berserkspirit",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying,glue_NOT"
  },
  {
    file="data/entities/animals/bigbat.xml",
    herd="bat",
    name="$animal_bigbat",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/bigfirebug.xml",
    herd="fly",
    name="$animal_bigfirebug",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/bigzombie.xml",
    herd="zombie",
    name="$animal_bigzombie",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,zombie"
  },
  {
    file="data/entities/animals/bigzombiehead.xml",
    herd="zombie",
    name="$animal_bigzombie",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,zombie,flying"
  },
  {
    file="data/entities/animals/bigzombietorso.xml",
    herd="zombie",
    name="$animal_bigzombie",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,zombie"
  },
  {
    file="data/entities/animals/blob.xml",
    herd="slimes",
    name="$animal_blob",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/bloodcrystal_physics.xml",
    herd="ghost",
    name="$animal_bloodcrystal_physics",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying,glue_NOT"
  },
  {
    file="data/entities/animals/bloom.xml",
    herd="flower",
    name="$animal_bloom",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/boss_alchemist/boss_alchemist.xml",
    herd="mage",
    name="$animal_boss_alchemist",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,glue_NOT,touchmagic_immunity,polymorphable_NOT,boss,miniboss,music_energy_100,necrobot_NOT,curse_NOT"
  },
  {
    file="data/entities/animals/boss_book/book_physics.xml",
    herd="robot",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,glue_NOT,robot"
  },
  {
    file="data/entities/animals/boss_centipede/boss_centipede.xml",
    herd="slimes",
    name="$animal_boss_centipede",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,hittable,homing_target,glue_NOT,polymorphable_NOT,boss,necrobot_NOT,sampo_or_boss,boss_centipede"
  },
  {
    file="data/entities/animals/boss_centipede/boss_centipede_minion.xml",
    herd="slimes",
    name="$animal_boss_centipede_minion",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying,glue_NOT,boss_centipede_minion"
  },
  {
    file="data/entities/animals/boss_dragon.xml",
    herd="boss_dragon",
    name="$animal_boss_dragon",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,hittable,homing_target,glue_NOT,polymorphable_NOT,necrobot_NOT,boss_dragon"
  },
  {
    file="data/entities/animals/boss_fish/fish_giga.xml",
    herd="eel",
    name="$animal_fish_giga",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,hittable,glue_NOT,touchmagic_immunity,polymorphable_NOT,necrobot_NOT,curse_NOT,hiteffect_enabled"
  },
  {
    file="data/entities/animals/boss_gate/gate_monster_a.xml",
    herd="ghost",
    name="$animal_gate_monster_a",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying,glue_NOT,necrobot_NOT,gate_monster"
  },
  {
    file="data/entities/animals/boss_gate/gate_monster_b.xml",
    herd="ghost",
    name="$animal_gate_monster_b",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying,glue_NOT,necrobot_NOT,gate_monster"
  },
  {
    file="data/entities/animals/boss_gate/gate_monster_c.xml",
    herd="ghost",
    name="$animal_gate_monster_c",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying,glue_NOT,necrobot_NOT,gate_monster"
  },
  {
    file="data/entities/animals/boss_gate/gate_monster_d.xml",
    herd="ghost",
    name="$animal_gate_monster_d",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying,glue_NOT,necrobot_NOT,gate_monster"
  },
  {
    file="data/entities/animals/boss_ghost/boss_ghost.xml",
    herd="ghost_boss",
    name="$animal_boss_ghost",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,hittable,glue_NOT,touchmagic_immunity,polymorphable_NOT,boss,miniboss,music_energy_100,necrobot_NOT,curse_NOT"
  },
  {
    file="data/entities/animals/boss_limbs/boss_limbs.xml",
    herd="boss_limbs",
    name="$animal_boss_limbs",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,glue_NOT,polymorphable_NOT,boss,miniboss,music_energy_100,necrobot_NOT"
  },
  {
    file="data/entities/animals/boss_limbs/slimeshooter_boss_limbs.xml",
    herd="boss_limbs",
    name="$animal_slimeshooter_boss_limbs",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying,slimeshooter_boss_limbs"
  },
  {
    file="data/entities/animals/boss_meat/boss_meat.xml",
    herd="slimes",
    name="$animal_boss_meat",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,glue_NOT,polymorphable_NOT,boss,miniboss,music_energy_100,necrobot_NOT"
  },
  {
    file="data/entities/animals/boss_pit/boss_pit.xml",
    herd="boss_limbs",
    name="$animal_boss_pit",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,glue_NOT,touchmagic_immunity,polymorphable_NOT,boss,miniboss,music_energy_100,necrobot_NOT,curse_NOT"
  },
  {
    file="data/entities/animals/boss_robot/boss_robot.xml",
    herd="robot",
    name="$animal_boss_robot",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,glue_NOT,polymorphable_NOT,boss,miniboss,music_energy_100,necrobot_NOT"
  },
  {
    file="data/entities/animals/boss_sky/boss_sky.xml",
    herd="ghost",
    name="$animal_boss_sky",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying,glue_NOT,touchmagic_immunity,polymorphable_NOT,boss,miniboss,necrobot_NOT,music_energy_000"
  },
  {
    file="data/entities/animals/boss_spirit/islandspirit.xml",
    herd="ghost",
    name="$animal_islandspirit",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,glue_NOT,touchmagic_immunity,polymorphable_NOT,boss,miniboss,music_energy_100,necrobot_NOT,curse_NOT,islandspirit"
  },
  {
    file="data/entities/animals/boss_wizard/boss_wizard.xml",
    herd="mage",
    name="$animal_boss_wizard",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,glue_NOT,touchmagic_immunity,polymorphable_NOT,boss,miniboss,music_energy_100,necrobot_NOT,boss_wizard"
  },
  {
    file="data/entities/animals/chest_leggy.xml",
    herd="ghost",
    name="$animal_lukki",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,hittable,homing_target,glue_NOT"
  },
  {
    file="data/entities/animals/chest_mimic.xml",
    herd="ghost",
    name="$animal_chest_mimic",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/confusespirit.xml",
    herd="ghost",
    name="$animal_confusespirit",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying,glue_NOT"
  },
  {
    file="data/entities/animals/coward.xml",
    herd="healer",
    name="$animal_coward",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/crypt/acidshooter.xml",
    herd="slimes",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/crypt/barfer.xml",
    herd="mage",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/crypt/crystal_physics.xml",
    herd="ghost",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying,glue_NOT"
  },
  {
    file="data/entities/animals/crypt/enlightened_alchemist.xml",
    herd="mage",
    name="$animal_enlightened_alchemist",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/crypt/failed_alchemist.xml",
    herd="mage",
    name="$animal_failed_alchemist",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/crypt/maggot.xml",
    herd="slimes",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/crypt/necromancer.xml",
    herd="mage",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying,polymorphable_NOT"
  },
  {
    file="data/entities/animals/crypt/phantom_a.xml",
    herd="ghost",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying,glue_NOT"
  },
  {
    file="data/entities/animals/crypt/phantom_b.xml",
    herd="ghost",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying,glue_NOT"
  },
  {
    file="data/entities/animals/crypt/skullfly.xml",
    herd="ghost",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/crypt/skullrat.xml",
    herd="ghost",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/crypt/tentacler.xml",
    herd="slimes",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/crypt/tentacler_small.xml",
    herd="slimes",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/crypt/thundermage.xml",
    herd="mage",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,thundermage"
  },
  {
    file="data/entities/animals/crypt/wizard_dark.xml",
    herd="mage",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/crypt/wizard_neutral.xml",
    herd="mage",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,polymorphable_NOT"
  },
  {
    file="data/entities/animals/crypt/wizard_poly.xml",
    herd="mage",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,polymorphable_NOT"
  },
  {
    file="data/entities/animals/crypt/wizard_returner.xml",
    herd="mage",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/crypt/wizard_tele.xml",
    herd="mage",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/crypt/worm.xml",
    herd="worm",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,hittable,homing_target,glue_NOT,worm"
  },
  {
    file="data/entities/animals/crypt/worm_skull.xml",
    herd="ghost",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,hittable,homing_target,glue_NOT,music_energy_000,worm"
  },
  {
    file="data/entities/animals/crystal_physics.xml",
    herd="ghost",
    name="$animal_crystal_physics",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying,glue_NOT"
  },
  {
    file="data/entities/animals/darkghost.xml",
    herd="ghost",
    name="$animal_darkghost",
    origin="Vanilla",
    tags="mortal,enemy,hittable,glue_NOT"
  },
  {
    file="data/entities/animals/deer.xml",
    herd="helpless",
    name="$animal_deer",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,hittable,homing_target,prey,helpless_animal"
  },
  {
    file="data/entities/animals/drone.xml",
    herd="robot",
    name="$animal_drone_physics",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,robot"
  },
  {
    file="data/entities/animals/drone_lasership.xml",
    herd="robot",
    name="$animal_drone_lasership",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,robot,drone_lasership"
  },
  {
    file="data/entities/animals/drone_physics.xml",
    herd="robot",
    name="$animal_drone_physics",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,glue_NOT,robot"
  },
  {
    file="data/entities/animals/drone_shield.xml",
    herd="robot",
    name="$animal_drone_shield",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,robot"
  },
  {
    file="data/entities/animals/drunk/miner.xml",
    herd="orcs",
    name="$animal_miner",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/drunk/miner_chef.xml",
    herd="orcs",
    name="$animal_cook",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/drunk/miner_fire.xml",
    herd="orcs",
    name="$animal_miner_fire",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/drunk/miner_weak.xml",
    herd="orcs",
    name="$animal_miner",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/drunk/scavenger_clusterbomb.xml",
    herd="orcs",
    name="$animal_scavenger_clusterbomb",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/drunk/scavenger_glue.xml",
    herd="orcs",
    name="$animal_scavenger_glue",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/drunk/scavenger_grenade.xml",
    herd="orcs",
    name="$animal_scavenger_grenade",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/drunk/scavenger_heal.xml",
    herd="healer",
    name="$animal_scavenger_heal",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/drunk/scavenger_invis.xml",
    herd="healer",
    name="$animal_scavenger_invis",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/drunk/scavenger_leader.xml",
    herd="orcs",
    name="$animal_scavenger_leader",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/drunk/scavenger_mine.xml",
    herd="orcs",
    name="$animal_scavenger_mine",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/drunk/scavenger_poison.xml",
    herd="orcs",
    name="$animal_scavenger_poison",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/drunk/scavenger_shield.xml",
    herd="healer",
    name="$animal_scavenger_shield",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/drunk/scavenger_smg.xml",
    herd="orcs",
    name="$animal_scavenger_smg",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/drunk/shotgunner.xml",
    herd="orcs",
    name="$animal_shotgunner",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/drunk/shotgunner_weak.xml",
    herd="orcs",
    name="$animal_shotgunner",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/drunk/sniper.xml",
    herd="orcs",
    name="$animal_sniper",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/duck.xml",
    herd="helpless",
    name="$animal_duck",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,hittable,homing_target,prey,helpless_animal"
  },
  {
    file="data/entities/animals/easter/sniper.xml",
    herd="orcs",
    name="$animal_sniper",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/eel.xml",
    herd="eel",
    name="$animal_eel",
    origin="Vanilla",
    tags="mortal,enemy,hittable,homing_target,destruction_target,glue_NOT"
  },
  {
    file="data/entities/animals/elk.xml",
    herd="helpless",
    name="$animal_elk",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,hittable,homing_target,prey,helpless_animal"
  },
  {
    file="data/entities/animals/enlightened_alchemist.xml",
    herd="mage",
    name="$animal_enlightened_alchemist",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/ethereal_being.xml",
    herd="ghost",
    name="$animal_ethereal_being",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,hittable,glue_NOT,polymorphable_NOT,boss_ghost_helper"
  },
  {
    file="data/entities/animals/failed_alchemist.xml",
    herd="mage",
    name="$animal_failed_alchemist",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/failed_alchemist_b.xml",
    herd="mage",
    name="$animal_failed_alchemist_b",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/firebug.xml",
    herd="fly",
    name="$animal_firebug",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/firemage.xml",
    herd="mage",
    name="$animal_firemage",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,firemage"
  },
  {
    file="data/entities/animals/firemage_weak.xml",
    herd="mage",
    name="$animal_firemage_weak",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,firemage"
  },
  {
    file="data/entities/animals/fireskull.xml",
    herd="fire",
    name="$animal_fireskull",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/fireskull_weak.xml",
    herd="fire",
    name="$animal_fireskull",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/fish.xml",
    herd="helpless",
    name="$animal_fish",
    origin="Vanilla",
    tags="mortal,hittable,prey,helpless_animal"
  },
  {
    file="data/entities/animals/fish_large.xml",
    herd="helpless",
    name="$animal_fish_large",
    origin="Vanilla",
    tags="mortal,hittable,prey,helpless_animal"
  },
  {
    file="data/entities/animals/flamer.xml",
    herd="robot",
    name="$animal_flamer",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,robot"
  },
  {
    file="data/entities/animals/fly.xml",
    herd="fly",
    name="$animal_fly",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/friend.xml",
    herd="orcs",
    name="$animal_friend",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying,big_friend"
  },
  {
    file="data/entities/animals/frog.xml",
    herd="slimes",
    name="$animal_frog",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/frog_big.xml",
    herd="slimes",
    name="$animal_frog_big",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/fungus.xml",
    herd="fungus",
    name="$animal_fungus",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/fungus_big.xml",
    herd="fungus",
    name="$animal_fungus_big",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/fungus_giga.xml",
    herd="fungus",
    name="$animal_fungus_giga",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/fungus_tiny.xml",
    herd="fungus",
    name="$animal_fungus_tiny",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,fungus_tiny_bad"
  },
  {
    file="data/entities/animals/gazer.xml",
    herd="slimes",
    name="$animal_gazer",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/ghost.xml",
    herd="ghost",
    name="$animal_ghost",
    origin="Vanilla",
    tags="mortal,enemy,hittable,glue_NOT,music_energy_000_near"
  },
  {
    file="data/entities/animals/ghoul.xml",
    herd="ghost",
    name="$animal_ghoul",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/giant.xml",
    herd="giant",
    name="$animal_giant",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/giantshooter.xml",
    herd="slimes",
    name="$animal_giantshooter",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/giantshooter_weak.xml",
    herd="slimes",
    name="$animal_giantshooter_weak",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/goblin_bomb.xml",
    herd="orcs",
    name="$animal_goblin_bomb",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/healerdrone_physics.xml",
    herd="healer",
    name="$animal_healerdrone_physics",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,glue_NOT,robot,healer"
  },
  {
    file="data/entities/animals/icemage.xml",
    herd="mage",
    name="$animal_icemage",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/icer.xml",
    herd="robot",
    name="$animal_icer",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,robot"
  },
  {
    file="data/entities/animals/iceskull.xml",
    herd="ice",
    name="$animal_iceskull",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/illusions/acidshooter.xml",
    herd="ghost",
    name="$animal_acidshooter",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying,glue_NOT"
  },
  {
    file="data/entities/animals/illusions/dark_alchemist.xml",
    herd="ghost",
    name="$animal_dark_alchemist",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/illusions/enlightened_alchemist.xml",
    herd="ghost",
    name="$animal_enlightened_alchemist",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,glue_NOT"
  },
  {
    file="data/entities/animals/illusions/scavenger_grenade.xml",
    herd="ghost",
    name="$animal_scavenger_grenade",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying,glue_NOT"
  },
  {
    file="data/entities/animals/illusions/scavenger_mine.xml",
    herd="ghost",
    name="$animal_scavenger_mine",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying,glue_NOT"
  },
  {
    file="data/entities/animals/illusions/shaman.xml",
    herd="ghost",
    name="$animal_shaman",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,shaman,glue_NOT"
  },
  {
    file="data/entities/animals/illusions/shaman_wind.xml",
    herd="ghost",
    name="$animal_shaman_wind",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/illusions/tank.xml",
    herd="ghost",
    name="$animal_tank",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,glue_NOT,robot"
  },
  {
    file="data/entities/animals/illusions/tentacler.xml",
    herd="ghost",
    name="$animal_tentacler",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying,glue_NOT"
  },
  {
    file="data/entities/animals/illusions/thundermage.xml",
    herd="ghost",
    name="$animal_thundermage",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,glue_NOT"
  },
  {
    file="data/entities/animals/illusions/wizard_swapper.xml",
    herd="ghost",
    name="$animal_wizard_swapper",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,glue_NOT"
  },
  {
    file="data/entities/animals/illusions/worm_big.xml",
    herd="ghost",
    name="$animal_worm_big",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,hittable,homing_target,glue_NOT,worm"
  },
  {
    file="data/entities/animals/lasershooter.xml",
    herd="slimes",
    name="$animal_lasershooter",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/longleg.xml",
    herd="spider",
    name="$animal_longleg",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/lukki/lukki.xml",
    herd="slimes",
    name="$animal_lukki",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,hittable,homing_target,glue_NOT,music_energy_100,lukki"
  },
  {
    file="data/entities/animals/lukki/lukki_creepy.xml",
    herd="spider",
    name="$animal_lukki_creepy",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,hittable,homing_target,glue_NOT,music_energy_100,lukki"
  },
  {
    file="data/entities/animals/lukki/lukki_creepy_long.xml",
    herd="spider",
    name="$animal_lukki_creepy_long",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,hittable,homing_target,glue_NOT,music_energy_100,lukki"
  },
  {
    file="data/entities/animals/lukki/lukki_dark.xml",
    herd="spider",
    name="$animal_lukki_dark",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,hittable,homing_target,glue_NOT,music_energy_100,lukki"
  },
  {
    file="data/entities/animals/lukki/lukki_longleg.xml",
    herd="spider",
    name="$animal_lukki_longleg",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,hittable,homing_target,glue_NOT,music_energy_100,lukki"
  },
  {
    file="data/entities/animals/lukki/lukki_tiny.xml",
    herd="slimes",
    name="$animal_lukki_tiny",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,hittable,homing_target,glue_NOT,music_energy_100,lukki"
  },
  {
    file="data/entities/animals/lurker.xml",
    herd="slimes",
    name="$animal_lurker",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/maggot.xml",
    herd="slimes",
    name="$animal_maggot",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/maggot_tiny/maggot_tiny.xml",
    herd="boss_dragon",
    name="$animal_maggot_tiny",
    origin="Vanilla",
    tags="teleportable_NOT,enemy,hittable,homing_target,glue_NOT,touchmagic_immunity,polymorphable_NOT,necrobot_NOT"
  },
  {
    file="data/entities/animals/meatmaggot.xml",
    herd="worm",
    name="$animal_meatmaggot",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,hittable,homing_target,glue_NOT,worm"
  },
  {
    file="data/entities/animals/mimic_physics.xml",
    herd="ghost",
    name="$animal_mimic_physics",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying,glue_NOT"
  },
  {
    file="data/entities/animals/miner.xml",
    herd="orcs",
    name="$animal_miner",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/miner_chef.xml",
    herd="orcs",
    name="$animal_cook",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/miner_fire.xml",
    herd="orcs",
    name="$animal_miner_fire",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/miner_hell.xml",
    herd="orcs",
    name="$animal_miner_hell",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/miner_santa.xml",
    herd="orcs",
    name="$animal_miner_santa",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/miner_weak.xml",
    herd="orcs",
    name="$animal_miner",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/miniblob.xml",
    herd="slimes",
    name="$animal_miniblob",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/missilecrab.xml",
    herd="robot",
    name="$animal_missilecrab",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,robot"
  },
  {
    file="data/entities/animals/monk.xml",
    herd="robot",
    name="$animal_monk",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/necrobot.xml",
    herd="robot",
    name="$animal_necrobot",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,robot,necrobot_NOT"
  },
  {
    file="data/entities/animals/necrobot_super.xml",
    herd="robot",
    name="$animal_necrobot_super",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,robot,necrobot_NOT"
  },
  {
    file="data/entities/animals/necromancer.xml",
    herd="mage",
    name="$animal_necromancer",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying,polymorphable_NOT"
  },
  {
    file="data/entities/animals/necromancer_shop.xml",
    herd="mage",
    name="$animal_necromancer_shop",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying,necromancer_shop,music_energy_100_near"
  },
  {
    file="data/entities/animals/necromancer_super.xml",
    herd="mage",
    name="$animal_necromancer_super",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying,polymorphable_NOT,necromancer_shop,music_energy_100_near,necromancer_super"
  },
  {
    file="data/entities/animals/parallel/alchemist/parallel_alchemist.xml",
    herd="mage",
    name="$animal_parallel_alchemist",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,touchmagic_immunity,polymorphable_NOT"
  },
  {
    file="data/entities/animals/parallel/tentacles/parallel_tentacles.xml",
    herd="boss_limbs",
    name="$animal_parallel_tentacles",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,glue_NOT,touchmagic_immunity,polymorphable_NOT"
  },
  {
    file="data/entities/animals/pebble_physics.xml",
    herd="giant",
    name="$animal_pebble",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,glue_NOT"
  },
  {
    file="data/entities/animals/phantom_a.xml",
    herd="ghost",
    name="$animal_phantom_a",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying,glue_NOT"
  },
  {
    file="data/entities/animals/phantom_b.xml",
    herd="ghost",
    name="$animal_phantom_b",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying,glue_NOT"
  },
  {
    file="data/entities/animals/playerghost.xml",
    herd="apparition",
    name="$animal_playerghost",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying,glue_NOT"
  },
  {
    file="data/entities/animals/rainforest/bloom.xml",
    herd="flower",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/rainforest/coward.xml",
    herd="healer",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/rainforest/flamer.xml",
    herd="robot",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,robot"
  },
  {
    file="data/entities/animals/rainforest/fly.xml",
    herd="fly",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/rainforest/fungus.xml",
    herd="fungus",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/rainforest/scavenger_clusterbomb.xml",
    herd="orcs",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/rainforest/scavenger_grenade.xml",
    herd="orcs",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/rainforest/scavenger_heal.xml",
    herd="healer",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/rainforest/scavenger_leader.xml",
    herd="orcs",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/rainforest/scavenger_mine.xml",
    herd="orcs",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/rainforest/scavenger_poison.xml",
    herd="orcs",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/rainforest/scavenger_smg.xml",
    herd="orcs",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/rainforest/shooterflower.xml",
    herd="flower",
    origin="Vanilla",
    tags="mortal,enemy,hittable,homing_target"
  },
  {
    file="data/entities/animals/rainforest/sniper.xml",
    herd="orcs",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/rat.xml",
    herd="rat",
    name="$animal_rat",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,rat"
  },
  {
    file="data/entities/animals/robobase/drone_lasership.xml",
    herd="robot",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,robot,drone_lasership"
  },
  {
    file="data/entities/animals/robobase/drone_shield.xml",
    herd="robot",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,robot"
  },
  {
    file="data/entities/animals/robobase/healerdrone_physics.xml",
    herd="healer",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,glue_NOT,robot,healer"
  },
  {
    file="data/entities/animals/robobase/monk.xml",
    herd="robot",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/robobase/tank_super.xml",
    herd="orcs",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,robot"
  },
  {
    file="data/entities/animals/robobase/turret_left.xml",
    herd="orcs",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,robot"
  },
  {
    file="data/entities/animals/robobase/turret_right.xml",
    herd="orcs",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,robot"
  },
  {
    file="data/entities/animals/roboguard.xml",
    herd="robot",
    name="$animal_roboguard",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,robot"
  },
  {
    file="data/entities/animals/roboguard_big.xml",
    herd="robot",
    name="$animal_piranha",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,robot"
  },
  {
    file="data/entities/animals/scavenger_clusterbomb.xml",
    herd="orcs",
    name="$animal_scavenger_clusterbomb",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/scavenger_glue.xml",
    herd="orcs",
    name="$animal_scavenger_glue",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/scavenger_grenade.xml",
    herd="orcs",
    name="$animal_scavenger_grenade",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/scavenger_heal.xml",
    herd="healer",
    name="$animal_scavenger_heal",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/scavenger_invis.xml",
    herd="healer",
    name="$animal_scavenger_invis",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/scavenger_leader.xml",
    herd="orcs",
    name="$animal_scavenger_leader",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/scavenger_mine.xml",
    herd="orcs",
    name="$animal_scavenger_mine",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/scavenger_poison.xml",
    herd="orcs",
    name="$animal_scavenger_poison",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/scavenger_shield.xml",
    herd="healer",
    name="$animal_scavenger_shield",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/scavenger_smg.xml",
    herd="orcs",
    name="$animal_scavenger_smg",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/scorpion.xml",
    herd="helpless",
    name="$animal_scorpion",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,hittable,homing_target,prey,helpless_animal"
  },
  {
    file="data/entities/animals/shaman.xml",
    herd="mage",
    name="$animal_shaman",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,shaman"
  },
  {
    file="data/entities/animals/sheep.xml",
    herd="helpless",
    name="$animal_sheep",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,hittable,homing_target,prey,helpless_animal,sheep"
  },
  {
    file="data/entities/animals/sheep_bat.xml",
    herd="helpless",
    name="$animal_sheep_bat",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,hittable,homing_target,prey,helpless_animal,sheep"
  },
  {
    file="data/entities/animals/sheep_fly.xml",
    herd="helpless",
    name="$animal_sheep_fly",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,hittable,homing_target,prey,helpless_animal,sheep"
  },
  {
    file="data/entities/animals/shooterflower.xml",
    herd="flower",
    name="$animal_shooterflower",
    origin="Vanilla",
    tags="mortal,enemy,hittable,homing_target"
  },
  {
    file="data/entities/animals/shotgunner.xml",
    herd="orcs",
    name="$animal_shotgunner",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/shotgunner_hell.xml",
    herd="orcs",
    name="$animal_shotgunner_hell",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/shotgunner_weak.xml",
    herd="orcs",
    name="$animal_shotgunner",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/skullfly.xml",
    herd="ghost",
    name="$animal_skullfly",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/skullrat.xml",
    herd="ghost",
    name="$animal_skullrat",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/skycrystal_physics.xml",
    herd="ghost",
    name="$animal_skycrystal_physics",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying,glue_NOT"
  },
  {
    file="data/entities/animals/skygazer.xml",
    herd="slimes",
    name="$animal_skygazer",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying,polymorphable_NOT"
  },
  {
    file="data/entities/animals/slimeshooter.xml",
    herd="slimes",
    name="$animal_slimeshooter",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/slimeshooter_nontoxic.xml",
    herd="slimes",
    name="$animal_slimeshooter",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/slimeshooter_weak.xml",
    herd="slimes",
    name="$animal_slimeshooter",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/slimespirit.xml",
    herd="ghost",
    name="$animal_slimespirit",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying,glue_NOT"
  },
  {
    file="data/entities/animals/sniper.xml",
    herd="orcs",
    name="$animal_sniper",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/sniper_hell.xml",
    herd="orcs",
    name="$animal_sniper_hell",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/spearbot.xml",
    herd="robot",
    name="$animal_spearbot",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,robot"
  },
  {
    file="data/entities/animals/special/minipit.xml",
    herd="slimes",
    name="$animal_minipit",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying,glue_NOT"
  },
  {
    file="data/entities/animals/spitmonster.xml",
    herd="slimes",
    name="$animal_spitmonster",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/statue.xml",
    herd="giant",
    name="$animal_statue",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/statue_physics.xml",
    herd="ghost",
    name="$animal_statue_physics",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying,glue_NOT"
  },
  {
    file="data/entities/animals/tank.xml",
    herd="orcs",
    name="$animal_tank",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,robot"
  },
  {
    file="data/entities/animals/tank_rocket.xml",
    herd="orcs",
    name="$animal_tank_rocket",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,robot"
  },
  {
    file="data/entities/animals/tank_super.xml",
    herd="orcs",
    name="$animal_tank",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,robot"
  },
  {
    file="data/entities/animals/tentacler.xml",
    herd="slimes",
    name="$animal_tentacler",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/tentacler_small.xml",
    herd="slimes",
    name="$animal_tentacler_small",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/the_end/bloodcrystal_physics.xml",
    herd="ghost",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying,glue_NOT"
  },
  {
    file="data/entities/animals/the_end/gazer.xml",
    herd="slimes",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/the_end/skycrystal_physics.xml",
    herd="ghost",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying,glue_NOT"
  },
  {
    file="data/entities/animals/the_end/skygazer.xml",
    herd="slimes",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying,polymorphable_NOT"
  },
  {
    file="data/entities/animals/the_end/spearbot.xml",
    herd="robot",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,robot"
  },
  {
    file="data/entities/animals/the_end/spitmonster.xml",
    herd="slimes",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/the_end/worm_end.xml",
    herd="worm",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,hittable,homing_target,glue_NOT,worm"
  },
  {
    file="data/entities/animals/the_end/worm_skull.xml",
    herd="ghost",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,hittable,homing_target,glue_NOT,music_energy_000,worm"
  },
  {
    file="data/entities/animals/thundermage.xml",
    herd="mage",
    name="$animal_thundermage",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,thundermage"
  },
  {
    file="data/entities/animals/thundermage_big.xml",
    herd="mage",
    name="$animal_thundermage_big",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,touchmagic_immunity,thundermage"
  },
  {
    file="data/entities/animals/thunderskull.xml",
    herd="ice",
    name="$animal_thunderskull",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/turret_left.xml",
    herd="orcs",
    name="$animal_turret",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,robot"
  },
  {
    file="data/entities/animals/turret_right.xml",
    herd="orcs",
    name="$animal_turret",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,robot"
  },
  {
    file="data/entities/animals/ultimate_killer.xml",
    herd="orcs",
    name="$animal_ultimate_killer",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying,small_friend"
  },
  {
    file="data/entities/animals/vault/acidshooter.xml",
    herd="slimes",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/vault/assassin.xml",
    herd="robot",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,robot"
  },
  {
    file="data/entities/animals/vault/bigzombie.xml",
    herd="zombie",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,zombie"
  },
  {
    file="data/entities/animals/vault/blob.xml",
    herd="slimes",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/vault/coward.xml",
    herd="healer",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/vault/drone_physics.xml",
    herd="robot",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,glue_NOT,robot"
  },
  {
    file="data/entities/animals/vault/firemage.xml",
    herd="mage",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,firemage"
  },
  {
    file="data/entities/animals/vault/flamer.xml",
    herd="robot",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,robot"
  },
  {
    file="data/entities/animals/vault/healerdrone_physics.xml",
    herd="healer",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,glue_NOT,robot,healer"
  },
  {
    file="data/entities/animals/vault/icer.xml",
    herd="robot",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,robot"
  },
  {
    file="data/entities/animals/vault/lasershooter.xml",
    herd="slimes",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/vault/maggot.xml",
    herd="slimes",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/vault/missilecrab.xml",
    herd="robot",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,robot"
  },
  {
    file="data/entities/animals/vault/roboguard.xml",
    herd="robot",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,robot"
  },
  {
    file="data/entities/animals/vault/scavenger_glue.xml",
    herd="orcs",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/vault/scavenger_grenade.xml",
    herd="orcs",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/vault/scavenger_heal.xml",
    herd="healer",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/vault/scavenger_leader.xml",
    herd="orcs",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/vault/scavenger_mine.xml",
    herd="orcs",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/vault/scavenger_smg.xml",
    herd="orcs",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/vault/sniper.xml",
    herd="orcs",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/vault/tank.xml",
    herd="orcs",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,robot"
  },
  {
    file="data/entities/animals/vault/tank_rocket.xml",
    herd="orcs",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,robot"
  },
  {
    file="data/entities/animals/vault/tank_super.xml",
    herd="orcs",
    name="$animal_tank",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,robot"
  },
  {
    file="data/entities/animals/vault/tentacler.xml",
    herd="slimes",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/vault/tentacler_small.xml",
    herd="slimes",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/vault/thundermage.xml",
    herd="mage",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,thundermage"
  },
  {
    file="data/entities/animals/vault/thunderskull.xml",
    herd="ice",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/vault/turret_left.xml",
    herd="orcs",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,robot"
  },
  {
    file="data/entities/animals/vault/turret_right.xml",
    herd="orcs",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,robot"
  },
  {
    file="data/entities/animals/vault/wizard_dark.xml",
    herd="mage",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/wand_ghost.xml",
    herd="ghost",
    name="$animal_wand_ghost",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying,glue_NOT,wand_ghost"
  },
  {
    file="data/entities/animals/wand_ghost_charmed.xml",
    herd="player",
    name="$animal_wand_ghost",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying,glue_NOT,wand_ghost"
  },
  {
    file="data/entities/animals/wand_ghost_with_sampo.xml",
    herd="player",
    name="$animal_wand_ghost",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying,glue_NOT,this_is_sampo,wand_ghost"
  },
  {
    file="data/entities/animals/weakspirit.xml",
    herd="ghost",
    name="$animal_weakspirit",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying,glue_NOT"
  },
  {
    file="data/entities/animals/wizard_dark.xml",
    herd="mage",
    name="$animal_wizard_dark",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/wizard_hearty.xml",
    herd="mage",
    name="$animal_wizard_hearty",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/wizard_homing.xml",
    herd="mage",
    name="$animal_wizard_homing",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/wizard_neutral.xml",
    herd="mage",
    name="$animal_wizard_neutral",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,polymorphable_NOT"
  },
  {
    file="data/entities/animals/wizard_poly.xml",
    herd="mage",
    name="$animal_wizard_poly",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,polymorphable_NOT"
  },
  {
    file="data/entities/animals/wizard_returner.xml",
    herd="mage",
    name="$animal_wizard_returner",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/wizard_swapper.xml",
    herd="mage_swapper",
    name="$animal_wizard_swapper",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/wizard_tele.xml",
    herd="mage",
    name="$animal_wizard_tele",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/wizard_twitchy.xml",
    herd="mage",
    name="$animal_wizard_twitchy",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/wizard_weaken.xml",
    herd="mage",
    name="$animal_wizard_weaken",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/wolf.xml",
    herd="wolf",
    name="$animal_wolf",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/animals/worm.xml",
    herd="worm",
    name="$animal_worm",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,hittable,homing_target,glue_NOT,worm"
  },
  {
    file="data/entities/animals/worm_big.xml",
    herd="worm",
    name="$animal_worm_big",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,hittable,homing_target,glue_NOT,worm"
  },
  {
    file="data/entities/animals/worm_end.xml",
    herd="worm",
    name="$animal_worm_end",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,hittable,homing_target,glue_NOT,worm"
  },
  {
    file="data/entities/animals/worm_skull.xml",
    herd="ghost",
    name="$animal_worm_skull",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,hittable,homing_target,glue_NOT,music_energy_000,worm"
  },
  {
    file="data/entities/animals/worm_tiny.xml",
    herd="worm",
    name="$animal_worm_tiny",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,hittable,homing_target,glue_NOT,worm"
  },
  {
    file="data/entities/animals/wraith.xml",
    herd="mage",
    name="$animal_wraith",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/wraith_glowing.xml",
    herd="mage",
    name="$animal_wraith_glowing",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/wraith_storm.xml",
    herd="mage",
    name="$animal_wraith_storm",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/animals/zombie.xml",
    herd="zombie",
    name="$animal_zombie",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,zombie"
  },
  {
    file="data/entities/animals/zombie_weak.xml",
    herd="zombie",
    name="$animal_zombie",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,zombie"
  },
  {
    file="data/entities/buildings/racing_cart.xml",
    herd="karl",
    origin="Vanilla",
    tags="racing_cart,moon_energy"
  },
  {
    file="data/entities/misc/fungus_projectile.xml",
    herd="fungus",
    name="$animal_fungus",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target"
  },
  {
    file="data/entities/misc/greed_curse/greed_ghost.xml",
    herd="-1",
    name="$animal_greed_ghost",
    origin="Vanilla",
    tags="teleportable_NOT,enemy,glue_NOT,polymorphable_NOT,greed_curse_ghost"
  },
  {
    file="data/entities/misc/homunculus.xml",
    herd="player",
    name="$animal_homunculus",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,human,hittable,destruction_target,homunculus"
  },
  {
    file="data/entities/misc/magic/heart_fullhp.xml",
    herd="boss_limbs",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,glue_NOT,touchmagic_immunity,polymorphable_NOT"
  },
  {
    file="data/entities/misc/perks/fungus.xml",
    herd="player",
    name="$animal_fungus_tiny_perk",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,human,hittable,destruction_target,perk_fungus_tiny"
  },
  {
    file="data/entities/misc/perks/lukki_minion.xml",
    herd="player",
    name="$perk_lukki_minion",
    origin="Vanilla",
    tags="mortal,hittable,glue_NOT,lukki"
  },
  {
    file="data/entities/misc/perks/plague_rats_rat.xml",
    herd="player",
    name="$animal_rat",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,human,hittable,destruction_target,rat,poopstone_immunity,plague_rat"
  },
  {
    file="data/entities/misc/player_drone.xml",
    herd="player",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,robot"
  },
  {
    file="data/entities/misc/player_drone_clone.xml",
    herd="player",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying,drone"
  },
  {
    file="data/entities/misc/tentacles.xml",
    herd="slimes",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,human,hittable,homing_target,destruction_target,flying"
  },
  {
    file="data/entities/misc/worm_big_worm_rain.xml",
    herd="worm",
    name="$animal_worm_big",
    origin="Vanilla",
    tags="mortal,teleportable_NOT,enemy,hittable,homing_target,glue_NOT,worm"
  },
  {
    file="data/entities/player.xml",
    herd="player",
    name="DEBUG_NAME:player",
    origin="Vanilla",
    tags="mortal,human,hittable,peasant,prey,player_unit,teleportable"
  },
  {
    file="data/entities/player_base.xml",
    herd="player",
    name="DEBUG_NAME:player",
    origin="Vanilla",
    tags="mortal,human,hittable,peasant,prey,player_unit,teleportable"
  },
  {
    file="data/entities/player_rng_items.xml",
    herd="player",
    name="DEBUG_NAME:player",
    origin="Vanilla",
    tags="mortal,human,hittable,peasant,prey,player_unit,teleportable"
  }
}
