return {
  {
    file="data/biome_impl/static_tile/chest_darkness.xml",
    item_name="$item_chest_treasure",
    origin="Vanilla",
    tags="teleportable_NOT,item_physics,chest,item_pickup,effectable_prop"
  },
  {
    file="data/entities/animals/boss_alchemist/key.xml",
    item_name="$item_key",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,alchemist_key"
  },
  {
    file="data/entities/animals/boss_centipede/rewards/gold_reward.xml",
    item_name="$reward_gold_statue",
    origin="Vanilla",
    tags="teleportable_NOT"
  },
  {
    file="data/entities/animals/boss_centipede/rewards/reward_almostpacifist.xml",
    item_name="$reward_almostpacifist",
    origin="Vanilla",
    tags="teleportable_NOT"
  },
  {
    file="data/entities/animals/boss_centipede/rewards/reward_clock.xml",
    item_name="$reward_clock",
    origin="Vanilla",
    tags="teleportable_NOT"
  },
  {
    file="data/entities/animals/boss_centipede/rewards/reward_crown.xml",
    item_name="$reward_crown",
    origin="Vanilla",
    tags="teleportable_NOT"
  },
  {
    file="data/entities/animals/boss_centipede/rewards/reward_dollar.xml",
    item_name="$reward_dollar",
    origin="Vanilla",
    tags="teleportable_NOT"
  },
  {
    file="data/entities/animals/boss_centipede/rewards/reward_kicksonly.xml",
    item_name="$reward_kicksonly",
    origin="Vanilla",
    tags="teleportable_NOT"
  },
  {
    file="data/entities/animals/boss_centipede/rewards/reward_minit.xml",
    item_name="$reward_minit",
    origin="Vanilla",
    tags="teleportable_NOT"
  },
  {
    file="data/entities/animals/boss_centipede/rewards/reward_nohit.xml",
    item_name="$reward_nohit",
    origin="Vanilla",
    tags="teleportable_NOT"
  },
  {
    file="data/entities/animals/boss_centipede/rewards/reward_nolla.xml",
    item_name="$reward_nolla",
    origin="Vanilla",
    tags="teleportable_NOT"
  },
  {
    file="data/entities/animals/boss_centipede/rewards/reward_notinkeringofwands.xml",
    item_name="$reward_notinkeringofwands",
    origin="Vanilla",
    tags="teleportable_NOT"
  },
  {
    file="data/entities/animals/boss_centipede/rewards/reward_nowands.xml",
    item_name="$reward_nowands",
    origin="Vanilla",
    tags="teleportable_NOT"
  },
  {
    file="data/entities/animals/boss_centipede/rewards/reward_peace.xml",
    item_name="$reward_peace",
    origin="Vanilla",
    tags="teleportable_NOT"
  },
  {
    file="data/entities/animals/boss_centipede/rewards/reward_sun.xml",
    item_name="$reward_sun",
    origin="Vanilla",
    tags="teleportable_NOT"
  },
  {
    file="data/entities/animals/boss_centipede/sampo.xml",
    item_name="$item_mcguffin_0",
    origin="Vanilla",
    tags="teleportable_NOT,sampo_or_boss,this_is_sampo"
  },
  {
    file="data/entities/base_item.xml",
    origin="Vanilla",
    tags="teleportable_NOT,item"
  },
  {
    file="data/entities/base_torch.xml",
    origin="Vanilla",
    tags="teleportable_NOT,prop,drillable,kickable,torch"
  },
  {
    file="data/entities/base_wand_physics.xml",
    origin="Vanilla",
    tags="teleportable_NOT"
  },
  {
    file="data/entities/buildings/chest_steel.xml",
    item_name="$item_chest_treasure",
    origin="Vanilla",
    tags="teleportable_NOT,item_physics,chest"
  },
  {
    file="data/entities/buildings/endcrystal.xml",
    item_name="Mystical Crystal Ball",
    origin="Vanilla",
    tags=""
  },
  {
    file="data/entities/items/books/base_book.xml",
    item_name="$booktitle01",
    origin="Vanilla",
    tags="tablet"
  },
  {
    file="data/entities/items/books/base_forged.xml",
    item_name="$booktitle01",
    origin="Vanilla",
    tags="tablet,forged_tablet"
  },
  {
    file="data/entities/items/books/book_00.xml",
    item_name="$booktitle00",
    origin="Vanilla",
    tags="tablet,normal_tablet"
  },
  {
    file="data/entities/items/books/book_01.xml",
    item_name="$booktitle01",
    origin="Vanilla",
    tags="tablet,normal_tablet"
  },
  {
    file="data/entities/items/books/book_02.xml",
    item_name="$booktitle02",
    origin="Vanilla",
    tags="forgeable,tablet,normal_tablet"
  },
  {
    file="data/entities/items/books/book_03.xml",
    item_name="$booktitle03",
    origin="Vanilla",
    tags="tablet,normal_tablet"
  },
  {
    file="data/entities/items/books/book_04.xml",
    item_name="$booktitle04",
    origin="Vanilla",
    tags="forgeable,tablet,normal_tablet"
  },
  {
    file="data/entities/items/books/book_05.xml",
    item_name="$booktitle05",
    origin="Vanilla",
    tags="forgeable,tablet,normal_tablet"
  },
  {
    file="data/entities/items/books/book_06.xml",
    item_name="$booktitle06",
    origin="Vanilla",
    tags="forgeable,tablet,normal_tablet"
  },
  {
    file="data/entities/items/books/book_07.xml",
    item_name="$booktitle07",
    origin="Vanilla",
    tags="forgeable,tablet,normal_tablet"
  },
  {
    file="data/entities/items/books/book_08.xml",
    item_name="$booktitle08",
    origin="Vanilla",
    tags="forgeable,tablet,normal_tablet"
  },
  {
    file="data/entities/items/books/book_09.xml",
    item_name="$booktitle09",
    origin="Vanilla",
    tags="forgeable,tablet,normal_tablet"
  },
  {
    file="data/entities/items/books/book_10.xml",
    item_name="$booktitle10",
    origin="Vanilla",
    tags="forgeable,tablet,normal_tablet"
  },
  {
    file="data/entities/items/books/book_all_spells.xml",
    item_name="$booktitle_allspells",
    origin="Vanilla",
    tags="tablet,normal_tablet"
  },
  {
    file="data/entities/items/books/book_barren.xml",
    item_name="$booktitle_barren",
    origin="Vanilla",
    tags="tablet,scroll"
  },
  {
    file="data/entities/items/books/book_bunker.xml",
    item_name="$booktitle_fisher",
    origin="Vanilla",
    tags="tablet,scroll"
  },
  {
    file="data/entities/items/books/book_corpse.xml",
    item_name="$booktitle_corpse",
    origin="Vanilla",
    tags="tablet,normal_tablet"
  },
  {
    file="data/entities/items/books/book_diamond.xml",
    item_name="$item_book_diamond",
    origin="Vanilla",
    tags="tablet,scroll"
  },
  {
    file="data/entities/items/books/book_essences.xml",
    item_name="$item_book_essences",
    origin="Vanilla",
    tags="tablet,scroll"
  },
  {
    file="data/entities/items/books/book_hint.xml",
    item_name="$item_book_hint",
    origin="Vanilla",
    tags="tablet,scroll"
  },
  {
    file="data/entities/items/books/book_mestari.xml",
    item_name="$booktitle_mestari",
    origin="Vanilla",
    tags="tablet,scroll"
  },
  {
    file="data/entities/items/books/book_moon.xml",
    item_name="$item_book_moon",
    origin="Vanilla",
    tags="tablet,scroll"
  },
  {
    file="data/entities/items/books/book_music_a.xml",
    item_name="$item_book_music",
    origin="Vanilla",
    tags="tablet,scroll"
  },
  {
    file="data/entities/items/books/book_music_b.xml",
    item_name="$item_book_music_b",
    origin="Vanilla",
    tags="tablet,scroll"
  },
  {
    file="data/entities/items/books/book_music_c.xml",
    item_name="$item_book_music_c",
    origin="Vanilla",
    tags="tablet,scroll"
  },
  {
    file="data/entities/items/books/book_robot.xml",
    item_name="$item_book_robot",
    origin="Vanilla",
    tags="tablet,scroll"
  },
  {
    file="data/entities/items/books/book_s_a.xml",
    item_name="$item_book_s_a",
    origin="Vanilla",
    tags="tablet,scroll"
  },
  {
    file="data/entities/items/books/book_s_b.xml",
    item_name="$item_book_s_a",
    origin="Vanilla",
    tags="tablet,scroll"
  },
  {
    file="data/entities/items/books/book_s_c.xml",
    item_name="$item_book_s_a",
    origin="Vanilla",
    tags="tablet,scroll"
  },
  {
    file="data/entities/items/books/book_s_d.xml",
    item_name="$item_book_s_a",
    origin="Vanilla",
    tags="tablet,scroll"
  },
  {
    file="data/entities/items/books/book_s_e.xml",
    item_name="$item_book_s_a",
    origin="Vanilla",
    tags="tablet,scroll"
  },
  {
    file="data/entities/items/books/book_tree.xml",
    item_name="$booktitle_tree",
    origin="Vanilla",
    tags="tablet,normal_tablet"
  },
  {
    file="data/entities/items/easter/beer_bottle.xml",
    item_name="$item_potion",
    origin="Vanilla",
    tags="hittable,teleportable_NOT",
    ui_name="$item_kaljapullo"
  },
  {
    file="data/entities/items/easter/minit_watering.xml",
    item_name="Potion",
    origin="Vanilla",
    tags="hittable,teleportable_NOT",
    ui_name="Watering can"
  },
  {
    file="data/entities/items/flute.xml",
    item_name="$item_ocarina",
    origin="Vanilla",
    tags="teleportable_NOT,item,wand"
  },
  {
    file="data/entities/items/kantele.xml",
    item_name="$item_kantele",
    origin="Vanilla",
    tags="teleportable_NOT,item,wand,kantele"
  },
  {
    file="data/entities/items/leukaluu_kantele.xml",
    item_name="$item_leukaluu_kantele",
    origin="Vanilla",
    tags="teleportable_NOT,item,wand"
  },
  {
    file="data/entities/items/orbs/orb_base.xml",
    item_name="$item_orb",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,polymorphable_NOT"
  },
  {
    file="data/entities/items/pickup/beamstone.xml",
    item_name="$item_mega_beam_stone",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup"
  },
  {
    file="data/entities/items/pickup/bloodmoney_10.xml",
    item_name="$item_bloodmoney_10",
    origin="Vanilla",
    tags="item_physics,gold_nugget",
    ui_name="$item_bloodmoney"
  },
  {
    file="data/entities/items/pickup/bloodmoney_1000.xml",
    item_name="$item_bloodmoney_1000",
    origin="Vanilla",
    tags="item_physics,gold_nugget",
    ui_name="$item_bloodmoney"
  },
  {
    file="data/entities/items/pickup/bloodmoney_10000.xml",
    item_name="$item_bloodmoney_10000",
    origin="Vanilla",
    tags="item_physics,gold_nugget",
    ui_name="$item_bloodmoney"
  },
  {
    file="data/entities/items/pickup/bloodmoney_200.xml",
    item_name="$item_bloodmoney_200",
    origin="Vanilla",
    tags="item_physics,gold_nugget",
    ui_name="$item_bloodmoney"
  },
  {
    file="data/entities/items/pickup/bloodmoney_200000.xml",
    item_name="$item_bloodmoney_200000",
    origin="Vanilla",
    tags="item_physics,gold_nugget",
    ui_name="$item_bloodmoney"
  },
  {
    file="data/entities/items/pickup/bloodmoney_50.xml",
    item_name="$item_bloodmoney_50",
    origin="Vanilla",
    tags="item_physics,gold_nugget",
    ui_name="$item_bloodmoney"
  },
  {
    file="data/entities/items/pickup/brimstone.xml",
    item_name="$item_brimstone",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,brimstone"
  },
  {
    file="data/entities/items/pickup/broken_wand.xml",
    item_name="$item_broken_wand",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,forgeable,broken_wand"
  },
  {
    file="data/entities/items/pickup/cape.xml",
    item_name="Fire protection cape",
    origin="Vanilla",
    tags="teleportable_NOT",
    ui_name="Cape upgrade"
  },
  {
    file="data/entities/items/pickup/chest_leggy.xml",
    item_name="$item_chest_treasure",
    origin="Vanilla",
    tags="teleportable_NOT,item_physics,item_pickup,effectable_prop"
  },
  {
    file="data/entities/items/pickup/chest_random.xml",
    item_name="$item_chest_treasure",
    origin="Vanilla",
    tags="teleportable_NOT,item_physics,chest,item_pickup,effectable_prop"
  },
  {
    file="data/entities/items/pickup/chest_random_super.xml",
    item_name="$item_chest_treasure",
    origin="Vanilla",
    tags="teleportable_NOT,item_physics,chest,item_pickup,effectable_prop",
    ui_name="$item_chest_treasure_super"
  },
  {
    file="data/entities/items/pickup/egg_fire.xml",
    item_name="$item_egg_fire",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,egg_item"
  },
  {
    file="data/entities/items/pickup/egg_hollow.xml",
    item_name="$item_egg_hollow",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,egg_item"
  },
  {
    file="data/entities/items/pickup/egg_monster.xml",
    item_name="$item_egg",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,egg_item"
  },
  {
    file="data/entities/items/pickup/egg_purple.xml",
    item_name="$item_egg_purple",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,egg_item"
  },
  {
    file="data/entities/items/pickup/egg_red.xml",
    item_name="$item_egg",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,egg_item"
  },
  {
    file="data/entities/items/pickup/egg_slime.xml",
    item_name="$item_egg_slime",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,egg_item"
  },
  {
    file="data/entities/items/pickup/egg_spiders.xml",
    item_name="$item_egg_purple",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,egg_item"
  },
  {
    file="data/entities/items/pickup/egg_worm.xml",
    item_name="$item_egg_worm",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,egg_item"
  },
  {
    file="data/entities/items/pickup/essence_air.xml",
    item_name="$item_essence_air",
    origin="Vanilla",
    tags="teleportable_NOT,item_pickup,essence"
  },
  {
    file="data/entities/items/pickup/essence_alcohol.xml",
    item_name="$item_essence_alcohol",
    origin="Vanilla",
    tags="teleportable_NOT,item_pickup,essence"
  },
  {
    file="data/entities/items/pickup/essence_fire.xml",
    item_name="$item_essence_fire",
    origin="Vanilla",
    tags="teleportable_NOT,item_pickup,essence"
  },
  {
    file="data/entities/items/pickup/essence_laser.xml",
    item_name="$item_essence_laser",
    origin="Vanilla",
    tags="teleportable_NOT,item_pickup,essence"
  },
  {
    file="data/entities/items/pickup/essence_water.xml",
    item_name="$item_essence_water",
    origin="Vanilla",
    tags="teleportable_NOT,item_pickup,essence"
  },
  {
    file="data/entities/items/pickup/evil_eye.xml",
    item_name="$item_evil_eye",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,evil_eye"
  },
  {
    file="data/entities/items/pickup/goldnugget.xml",
    item_name="$item_goldnugget_10",
    origin="Vanilla",
    tags="item_physics,gold_nugget",
    ui_name="$item_goldnugget"
  },
  {
    file="data/entities/items/pickup/goldnugget_10.xml",
    item_name="$item_goldnugget_10",
    origin="Vanilla",
    tags="item_physics,gold_nugget",
    ui_name="$item_goldnugget"
  },
  {
    file="data/entities/items/pickup/goldnugget_1000.xml",
    item_name="$item_goldnugget_1000",
    origin="Vanilla",
    tags="item_physics,gold_nugget",
    ui_name="$item_goldnugget"
  },
  {
    file="data/entities/items/pickup/goldnugget_10000.xml",
    item_name="$item_goldnugget_10000",
    origin="Vanilla",
    tags="item_physics,gold_nugget",
    ui_name="$item_goldnugget"
  },
  {
    file="data/entities/items/pickup/goldnugget_200.xml",
    item_name="$item_goldnugget_200",
    origin="Vanilla",
    tags="item_physics,gold_nugget",
    ui_name="$item_goldnugget"
  },
  {
    file="data/entities/items/pickup/goldnugget_200000.xml",
    item_name="$item_goldnugget_200000",
    origin="Vanilla",
    tags="item_physics,gold_nugget",
    ui_name="$item_goldnugget"
  },
  {
    file="data/entities/items/pickup/goldnugget_50.xml",
    item_name="$item_goldnugget_50",
    origin="Vanilla",
    tags="item_physics,gold_nugget",
    ui_name="$item_goldnugget"
  },
  {
    file="data/entities/items/pickup/gourd.xml",
    item_name="$item_gourd",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,gourd"
  },
  {
    file="data/entities/items/pickup/greed_curse.xml",
    item_name="$item_essence_greed",
    origin="Vanilla",
    tags="teleportable_NOT,item_pickup,essence"
  },
  {
    file="data/entities/items/pickup/heart.xml",
    item_name="$item_heart",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_pickup,drillable"
  },
  {
    file="data/entities/items/pickup/heart_better.xml",
    item_name="$item_heart_better",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_pickup,drillable"
  },
  {
    file="data/entities/items/pickup/heart_evil.xml",
    item_name="$item_heart",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_pickup,drillable"
  },
  {
    file="data/entities/items/pickup/heart_fullhp.xml",
    item_name="$item_heart_fullhp",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_pickup,drillable"
  },
  {
    file="data/entities/items/pickup/jar.xml",
    item_name="$item_jar",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,potion"
  },
  {
    file="data/entities/items/pickup/moon.xml",
    item_name="$item_moon",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_pickup,moon_energy"
  },
  {
    file="data/entities/items/pickup/musicstone.xml",
    item_name="$item_musicstone",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,moon_energy"
  },
  {
    file="data/entities/items/pickup/perk_reroll.xml",
    item_name="$item_perk_reroll",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item,glue_NOT,perk_reroll_machine,item_shop"
  },
  {
    file="data/entities/items/pickup/physics_die.xml",
    item_name="$item_die",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup"
  },
  {
    file="data/entities/items/pickup/physics_gold_orb.xml",
    item_name="$item_gold_orb",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup"
  },
  {
    file="data/entities/items/pickup/physics_gold_orb_greed.xml",
    item_name="$item_gold_orb_greed",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup"
  },
  {
    file="data/entities/items/pickup/physics_greed_die.xml",
    item_name="$item_greed_die",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup"
  },
  {
    file="data/entities/items/pickup/poopstone.xml",
    item_name="$item_kakka",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,poopstone"
  },
  {
    file="data/entities/items/pickup/potion.xml",
    item_name="$item_potion",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,potion"
  },
  {
    file="data/entities/items/pickup/potion_aggressive.xml",
    item_name="$item_potion",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,potion,projectile_item"
  },
  {
    file="data/entities/items/pickup/potion_mimic.xml",
    item_name="$item_potion_mimic",
    origin="Vanilla",
    tags="teleportable_NOT,item_physics,item_pickup,effectable_prop"
  },
  {
    file="data/entities/items/pickup/powder_stash.xml",
    item_name="$item_powder_stash_3",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,powder_stash"
  },
  {
    file="data/entities/items/pickup/runestones/runestone_base.xml",
    item_name="$item_runestone_slow",
    origin="Vanilla",
    tags="teleportable_NOT,item_physics,item_pickup"
  },
  {
    file="data/entities/items/pickup/runestones/runestone_disc.xml",
    item_name="$item_runestone_disc",
    origin="Vanilla",
    tags="teleportable_NOT,item_physics,item_pickup"
  },
  {
    file="data/entities/items/pickup/runestones/runestone_fireball.xml",
    item_name="$item_runestone_fireball",
    origin="Vanilla",
    tags="teleportable_NOT,item_physics,item_pickup"
  },
  {
    file="data/entities/items/pickup/runestones/runestone_laser.xml",
    item_name="$item_runestone_laser",
    origin="Vanilla",
    tags="teleportable_NOT,item_physics,item_pickup"
  },
  {
    file="data/entities/items/pickup/runestones/runestone_lava.xml",
    item_name="$item_runestone_lava",
    origin="Vanilla",
    tags="teleportable_NOT,item_physics,item_pickup"
  },
  {
    file="data/entities/items/pickup/runestones/runestone_metal.xml",
    item_name="$item_runestone_metal",
    origin="Vanilla",
    tags="teleportable_NOT,item_physics,item_pickup"
  },
  {
    file="data/entities/items/pickup/runestones/runestone_null.xml",
    item_name="$item_runestone_null",
    origin="Vanilla",
    tags="teleportable_NOT,item_physics,item_pickup"
  },
  {
    file="data/entities/items/pickup/runestones/runestone_slow.xml",
    item_name="$item_runestone_slow",
    origin="Vanilla",
    tags="teleportable_NOT,item_physics,item_pickup"
  },
  {
    file="data/entities/items/pickup/safe_haven.xml",
    item_name="$item_safe_haven",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics"
  },
  {
    file="data/entities/items/pickup/spell_refresh.xml",
    item_name="$item_spell_refresh",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_pickup,drillable"
  },
  {
    file="data/entities/items/pickup/stonestone.xml",
    item_name="$item_stonestone",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,stonestone"
  },
  {
    file="data/entities/items/pickup/summon_portal_broken.xml",
    item_name="$action_broken_spell",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,forgeable,card_summon_portal_broken"
  },
  {
    file="data/entities/items/pickup/sun/sunseed.xml",
    item_name="$item_sunseed",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,seed_a"
  },
  {
    file="data/entities/items/pickup/sun/sunstone.xml",
    item_name="$item_seed_c",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,seed_b"
  },
  {
    file="data/entities/items/pickup/test/pouch.xml",
    item_name="$item_potion",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics"
  },
  {
    file="data/entities/items/pickup/test/pouch_static.xml",
    item_name="$item_potion",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics"
  },
  {
    file="data/entities/items/pickup/thunderstone.xml",
    item_name="$item_thunderstone",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,thunderstone"
  },
  {
    file="data/entities/items/pickup/utility_box.xml",
    item_name="$item_utility_box",
    origin="Vanilla",
    tags="teleportable_NOT,item_physics,item_pickup,effectable_prop,utility_box"
  },
  {
    file="data/entities/items/pickup/wandstone.xml",
    item_name="$item_wandstone",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup"
  },
  {
    file="data/entities/items/pickup/waterstone.xml",
    item_name="$item_waterstone",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,waterstone"
  },
  {
    file="data/entities/items/starting_bomb_wand.xml",
    item_name="bomb_wand",
    origin="Vanilla",
    tags="teleportable_NOT,item,wand"
  },
  {
    file="data/entities/items/starting_bomb_wand_rng.xml",
    item_name="bomb_wand",
    origin="Vanilla",
    tags="teleportable_NOT,item,wand"
  },
  {
    file="data/entities/items/starting_bomb_wand_rng_daily.xml",
    item_name="bomb_wand",
    origin="Vanilla",
    tags="teleportable_NOT,item,wand"
  },
  {
    file="data/entities/items/starting_wand.xml",
    item_name="default_gun",
    origin="Vanilla",
    tags="teleportable_NOT,item,wand,sacred_wand,first_wand"
  },
  {
    file="data/entities/items/starting_wand_rng.xml",
    item_name="default_gun",
    origin="Vanilla",
    tags="teleportable_NOT,item,wand"
  },
  {
    file="data/entities/items/starting_wand_rng_daily.xml",
    item_name="default_gun",
    origin="Vanilla",
    tags="teleportable_NOT,item,wand"
  },
  {
    file="data/entities/items/wand_daily_01.xml",
    origin="Vanilla",
    tags="teleportable_NOT,item,wand"
  },
  {
    file="data/entities/items/wand_daily_02.xml",
    origin="Vanilla",
    tags="teleportable_NOT,item,wand"
  },
  {
    file="data/entities/items/wand_daily_03.xml",
    origin="Vanilla",
    tags="teleportable_NOT,item,wand"
  },
  {
    file="data/entities/items/wand_daily_04.xml",
    origin="Vanilla",
    tags="teleportable_NOT,item,wand"
  },
  {
    file="data/entities/items/wand_daily_05.xml",
    origin="Vanilla",
    tags="teleportable_NOT,item,wand"
  },
  {
    file="data/entities/items/wand_daily_06.xml",
    origin="Vanilla",
    tags="teleportable_NOT,item,wand"
  },
  {
    file="data/entities/items/wand_level_01.xml",
    origin="Vanilla",
    tags="teleportable_NOT,item,wand"
  },
  {
    file="data/entities/items/wand_level_01_better.xml",
    origin="Vanilla",
    tags="teleportable_NOT,item,wand"
  },
  {
    file="data/entities/items/wand_level_01_p.xml",
    origin="Vanilla",
    tags="teleportable_NOT,wand"
  },
  {
    file="data/entities/items/wand_level_02.xml",
    origin="Vanilla",
    tags="teleportable_NOT,item,wand"
  },
  {
    file="data/entities/items/wand_level_02_better.xml",
    origin="Vanilla",
    tags="teleportable_NOT,item,wand"
  },
  {
    file="data/entities/items/wand_level_02_p.xml",
    origin="Vanilla",
    tags="teleportable_NOT,wand"
  },
  {
    file="data/entities/items/wand_level_03.xml",
    origin="Vanilla",
    tags="teleportable_NOT,item,wand"
  },
  {
    file="data/entities/items/wand_level_03_better.xml",
    origin="Vanilla",
    tags="teleportable_NOT,item,wand"
  },
  {
    file="data/entities/items/wand_level_03_p.xml",
    origin="Vanilla",
    tags="teleportable_NOT,wand"
  },
  {
    file="data/entities/items/wand_level_04.xml",
    origin="Vanilla",
    tags="teleportable_NOT,item,wand"
  },
  {
    file="data/entities/items/wand_level_04_better.xml",
    origin="Vanilla",
    tags="teleportable_NOT,item,wand"
  },
  {
    file="data/entities/items/wand_level_04_p.xml",
    origin="Vanilla",
    tags="teleportable_NOT,wand"
  },
  {
    file="data/entities/items/wand_level_05.xml",
    origin="Vanilla",
    tags="teleportable_NOT,item,wand"
  },
  {
    file="data/entities/items/wand_level_05_better.xml",
    origin="Vanilla",
    tags="teleportable_NOT,item,wand"
  },
  {
    file="data/entities/items/wand_level_05_p.xml",
    origin="Vanilla",
    tags="teleportable_NOT,wand"
  },
  {
    file="data/entities/items/wand_level_06.xml",
    origin="Vanilla",
    tags="teleportable_NOT,item,wand"
  },
  {
    file="data/entities/items/wand_level_06_better.xml",
    origin="Vanilla",
    tags="teleportable_NOT,item,wand"
  },
  {
    file="data/entities/items/wand_level_06_p.xml",
    origin="Vanilla",
    tags="teleportable_NOT,wand"
  },
  {
    file="data/entities/items/wand_level_10.xml",
    origin="Vanilla",
    tags="teleportable_NOT,item,wand"
  },
  {
    file="data/entities/items/wand_petri.xml",
    origin="Vanilla",
    tags="teleportable_NOT,item,wand"
  },
  {
    file="data/entities/items/wand_unshuffle_01.xml",
    origin="Vanilla",
    tags="teleportable_NOT,item,wand"
  },
  {
    file="data/entities/items/wand_unshuffle_01_p.xml",
    origin="Vanilla",
    tags="teleportable_NOT,wand"
  },
  {
    file="data/entities/items/wand_unshuffle_02.xml",
    origin="Vanilla",
    tags="teleportable_NOT,item,wand"
  },
  {
    file="data/entities/items/wand_unshuffle_02_p.xml",
    origin="Vanilla",
    tags="teleportable_NOT,wand"
  },
  {
    file="data/entities/items/wand_unshuffle_03.xml",
    origin="Vanilla",
    tags="teleportable_NOT,item,wand"
  },
  {
    file="data/entities/items/wand_unshuffle_03_p.xml",
    origin="Vanilla",
    tags="teleportable_NOT,wand"
  },
  {
    file="data/entities/items/wand_unshuffle_04.xml",
    origin="Vanilla",
    tags="teleportable_NOT,item,wand"
  },
  {
    file="data/entities/items/wand_unshuffle_04_p.xml",
    origin="Vanilla",
    tags="teleportable_NOT,wand"
  },
  {
    file="data/entities/items/wand_unshuffle_05.xml",
    origin="Vanilla",
    tags="teleportable_NOT,item,wand"
  },
  {
    file="data/entities/items/wand_unshuffle_05_p.xml",
    origin="Vanilla",
    tags="teleportable_NOT,wand"
  },
  {
    file="data/entities/items/wand_unshuffle_06.xml",
    origin="Vanilla",
    tags="teleportable_NOT,item,wand"
  },
  {
    file="data/entities/items/wand_unshuffle_06_p.xml",
    origin="Vanilla",
    tags="teleportable_NOT,wand"
  },
  {
    file="data/entities/items/wand_unshuffle_10.xml",
    origin="Vanilla",
    tags="teleportable_NOT,item,wand"
  },
  {
    file="data/entities/items/wands/custom/digger_01.xml",
    item_name="fire_wand",
    origin="Vanilla",
    tags="teleportable_NOT,item,wand"
  },
  {
    file="data/entities/items/wands/experimental/experimental_wand_1.xml",
    item_name="$item_wand_experimental_1",
    origin="Vanilla",
    tags="teleportable_NOT,item,wand,wand_experimental"
  },
  {
    file="data/entities/items/wands/experimental/experimental_wand_2.xml",
    item_name="$item_wand_experimental_2",
    origin="Vanilla",
    tags="teleportable_NOT,item,wand,wand_experimental"
  },
  {
    file="data/entities/items/wands/experimental/experimental_wand_3.xml",
    item_name="$item_wand_experimental_1",
    origin="Vanilla",
    tags="teleportable_NOT,item,wand"
  },
  {
    file="data/entities/items/wands/experimental/experimental_wand_4.xml",
    item_name="$item_chainsaw",
    origin="Vanilla",
    tags="teleportable_NOT,item,wand"
  },
  {
    file="data/entities/items/wands/level_01/base_wand_level_1.xml",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,wand"
  },
  {
    file="data/entities/items/wands/level_01/wand_001.xml",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,wand"
  },
  {
    file="data/entities/items/wands/level_01/wand_002.xml",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,wand"
  },
  {
    file="data/entities/items/wands/level_01/wand_003.xml",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,wand"
  },
  {
    file="data/entities/items/wands/level_01/wand_004.xml",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,wand"
  },
  {
    file="data/entities/items/wands/level_01/wand_005.xml",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,wand"
  },
  {
    file="data/entities/items/wands/level_01/wand_006.xml",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,wand"
  },
  {
    file="data/entities/items/wands/level_01/wand_007.xml",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,wand"
  },
  {
    file="data/entities/items/wands/level_01/wand_008.xml",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,wand"
  },
  {
    file="data/entities/items/wands/level_01/wand_009.xml",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,wand"
  },
  {
    file="data/entities/items/wands/level_01/wand_010.xml",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item,wand"
  },
  {
    file="data/entities/items/wands/level_01/wand_011.xml",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item,wand"
  },
  {
    file="data/entities/items/wands/level_01/wand_012.xml",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item,wand"
  },
  {
    file="data/entities/items/wands/level_01/wand_013.xml",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item,wand"
  },
  {
    file="data/entities/items/wands/level_01/wand_014.xml",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item,wand"
  },
  {
    file="data/entities/items/wands/level_01/wand_015.xml",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item,wand"
  },
  {
    file="data/entities/items/wands/level_01/wand_016.xml",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item,wand"
  },
  {
    file="data/entities/items/wands/level_01/wand_017.xml",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item,wand"
  },
  {
    file="data/entities/items/wands/wand_good/wand_good_1.xml",
    item_name="$item_wand_good_1",
    origin="Vanilla",
    tags="teleportable_NOT,item,wand,wand_good"
  },
  {
    file="data/entities/items/wands/wand_good/wand_good_2.xml",
    item_name="$item_wand_good_2",
    origin="Vanilla",
    tags="teleportable_NOT,item,wand,wand_good"
  },
  {
    file="data/entities/items/wands/wand_good/wand_good_3.xml",
    item_name="$item_wand_good_3",
    origin="Vanilla",
    tags="teleportable_NOT,item,wand,wand_good"
  },
  { file="data/entities/misc/test_bullet.xml", origin="Vanilla", tags="hittable" },
  {
    file="data/entities/projectiles/cocktail.xml",
    item_name="$item_cocktail",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,projectile_item"
  },
  {
    file="data/scripts/streaming_integration/entities/chest_random.xml",
    item_name="$item_chest_treasure",
    origin="Vanilla",
    tags="teleportable_NOT,item_physics,chest"
  },
  {
    file="data/scripts/streaming_integration/entities/spell_refresh.xml",
    item_name="$item_spell_refresh",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,drillable"
  },
  {
    file="data/scripts/streaming_integration/entities/wand_level_01.xml",
    origin="Vanilla",
    tags="teleportable_NOT,item,wand"
  },
  {
    file="data/scripts/streaming_integration/entities/wand_level_02.xml",
    origin="Vanilla",
    tags="teleportable_NOT,item,wand"
  },
  {
    file="data/scripts/streaming_integration/entities/wand_level_03.xml",
    origin="Vanilla",
    tags="teleportable_NOT,item,wand"
  },
  {
    file="mods/starting_loadouts/files/butcher/potion_berserk.xml",
    item_name="$item_potion",
    origin="starting_loadouts",
    tags="hittable,teleportable_NOT,item_physics,potion"
  },
  {
    file="mods/starting_loadouts/files/butcher/potion_blood.xml",
    item_name="$item_potion",
    origin="starting_loadouts",
    tags="hittable,teleportable_NOT,item_physics,potion"
  },
  {
    file="mods/starting_loadouts/files/butcher/wands/wand_1.xml",
    item_name="butcher_wand",
    origin="starting_loadouts",
    tags="teleportable_NOT,item,wand"
  },
  {
    file="mods/starting_loadouts/files/butcher/wands/wand_2.xml",
    item_name="butcher_wand",
    origin="starting_loadouts",
    tags="teleportable_NOT,item,wand"
  },
  {
    file="mods/starting_loadouts/files/eldritch/potion_teleport.xml",
    item_name="$item_potion",
    origin="starting_loadouts",
    tags="hittable,teleportable_NOT,item_physics,potion"
  },
  {
    file="mods/starting_loadouts/files/eldritch/wands/wand_1.xml",
    item_name="eldritch_wand",
    origin="starting_loadouts",
    tags="teleportable_NOT,item,wand"
  },
  {
    file="mods/starting_loadouts/files/eldritch/wands/wand_2.xml",
    item_name="eldritch_wand",
    origin="starting_loadouts",
    tags="teleportable_NOT,item,wand"
  },
  {
    file="mods/starting_loadouts/files/eldritch/wands/wand_3.xml",
    item_name="slime_wand",
    origin="starting_loadouts",
    tags="teleportable_NOT,item,wand"
  },
  {
    file="mods/starting_loadouts/files/fire/potion_fire.xml",
    item_name="$item_potion",
    origin="starting_loadouts",
    tags="hittable,teleportable_NOT,item_physics,potion"
  },
  {
    file="mods/starting_loadouts/files/fire/wands/wand_1.xml",
    item_name="fire_wand",
    origin="starting_loadouts",
    tags="teleportable_NOT,item,wand"
  },
  {
    file="mods/starting_loadouts/files/fire/wands/wand_2.xml",
    item_name="fire_wand",
    origin="starting_loadouts",
    tags="teleportable_NOT,item,wand"
  },
  {
    file="mods/starting_loadouts/files/slime/potion_slime.xml",
    item_name="$item_potion",
    origin="starting_loadouts",
    tags="hittable,teleportable_NOT,item_physics,potion"
  },
  {
    file="mods/starting_loadouts/files/slime/wands/wand_1.xml",
    item_name="slime_wand",
    origin="starting_loadouts",
    tags="teleportable_NOT,item,wand"
  },
  {
    file="mods/starting_loadouts/files/slime/wands/wand_2.xml",
    item_name="slime_wand",
    origin="starting_loadouts",
    tags="teleportable_NOT,item,wand"
  },
  {
    file="mods/starting_loadouts/files/slime/wands/wand_3.xml",
    item_name="slime_wand",
    origin="starting_loadouts",
    tags="teleportable_NOT,item,wand"
  },
  {
    file="mods/starting_loadouts/files/summoner/wands/wand_1.xml",
    item_name="summon_wand",
    origin="starting_loadouts",
    tags="teleportable_NOT,item,wand"
  },
  {
    file="mods/starting_loadouts/files/summoner/wands/wand_2.xml",
    item_name="summon_wand",
    origin="starting_loadouts",
    tags="teleportable_NOT,item,wand"
  },
  {
    file="mods/starting_loadouts/files/thunder/wands/wand_1.xml",
    item_name="thunder_wand",
    origin="starting_loadouts",
    tags="teleportable_NOT,item,wand"
  },
  {
    file="mods/starting_loadouts/files/thunder/wands/wand_2.xml",
    item_name="thunder_wand",
    origin="starting_loadouts",
    tags="teleportable_NOT,item,wand"
  }
}
