return {
  {
    file="data/entities/animals/boss_alchemist/key.xml",
    image="data/items_gfx/key.png",
    material="item_box2d_glass",
    name="key",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,alchemist_key"
  },
  {
    file="data/entities/animals/boss_centipede/body_chunks.xml",
    image="data/entities/animals/boss_centipede/body_chunk_01.png",
    material="meat_slime_green",
    name="body_chunks",
    origin="Vanilla",
    tags="hittable"
  },
  {
    file="data/entities/animals/boss_centipede/rewards/giant_dollar.xml",
    image="data/entities/animals/boss_centipede/rewards/giant_dollar.png",
    material="gold_b2",
    name="giant_dollar",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/animals/boss_centipede/rewards/gold_reward.xml",
    image="data/entities/animals/boss_centipede/rewards/gold_reward_sprite.png",
    material="metal_prop",
    name="gold_reward",
    origin="Vanilla",
    tags="teleportable_NOT"
  },
  {
    file="data/entities/animals/boss_centipede/rewards/reward_almostpacifist.xml",
    image="data/entities/animals/boss_centipede/rewards/reward_almostpacifist.png",
    material="metal_prop",
    name="reward_almostpacifist",
    origin="Vanilla",
    tags="teleportable_NOT"
  },
  {
    file="data/entities/animals/boss_centipede/rewards/reward_clock.xml",
    image="data/entities/animals/boss_centipede/rewards/reward_clock.png",
    material="metal_prop",
    name="reward_clock",
    origin="Vanilla",
    tags="teleportable_NOT"
  },
  {
    file="data/entities/animals/boss_centipede/rewards/reward_crown.xml",
    image="data/entities/animals/boss_centipede/rewards/reward_crown.png",
    material="metal_prop",
    name="reward_crown",
    origin="Vanilla",
    tags="teleportable_NOT"
  },
  {
    file="data/entities/animals/boss_centipede/rewards/reward_dollar.xml",
    image="data/entities/animals/boss_centipede/rewards/reward_dollar.png",
    material="metal_prop",
    name="reward_dollar",
    origin="Vanilla",
    tags="teleportable_NOT"
  },
  {
    file="data/entities/animals/boss_centipede/rewards/reward_kicksonly.xml",
    image="data/entities/animals/boss_centipede/rewards/reward_kicksonly.png",
    material="metal_prop",
    name="reward_kicksonly",
    origin="Vanilla",
    tags="teleportable_NOT"
  },
  {
    file="data/entities/animals/boss_centipede/rewards/reward_minit.xml",
    image="data/entities/animals/boss_centipede/rewards/reward_minit.png",
    material="metal_prop",
    name="reward_minit",
    origin="Vanilla",
    tags="teleportable_NOT"
  },
  {
    file="data/entities/animals/boss_centipede/rewards/reward_nohit.xml",
    image="data/entities/animals/boss_centipede/rewards/reward_nohit.png",
    material="metal_prop",
    name="reward_nohit",
    origin="Vanilla",
    tags="teleportable_NOT"
  },
  {
    file="data/entities/animals/boss_centipede/rewards/reward_nolla.xml",
    image="data/entities/animals/boss_centipede/rewards/reward_nolla.png",
    material="metal_prop",
    name="reward_nolla",
    origin="Vanilla",
    tags="teleportable_NOT"
  },
  {
    file="data/entities/animals/boss_centipede/rewards/reward_notinkeringofwands.xml",
    image="data/entities/animals/boss_centipede/rewards/reward_notinkeringofwands.png",
    material="metal_prop",
    name="reward_notinkeringofwands",
    origin="Vanilla",
    tags="teleportable_NOT"
  },
  {
    file="data/entities/animals/boss_centipede/rewards/reward_nowands.xml",
    image="data/entities/animals/boss_centipede/rewards/reward_nowands.png",
    material="metal_prop",
    name="reward_nowands",
    origin="Vanilla",
    tags="teleportable_NOT"
  },
  {
    file="data/entities/animals/boss_centipede/rewards/reward_peace.xml",
    image="data/entities/animals/boss_centipede/rewards/reward_peace.png",
    material="gold_b2",
    name="reward_peace",
    origin="Vanilla",
    tags="teleportable_NOT"
  },
  {
    file="data/entities/animals/boss_centipede/rewards/reward_sun.xml",
    image="data/entities/animals/boss_centipede/rewards/reward_sun.png",
    material="metal_prop",
    name="reward_sun",
    origin="Vanilla",
    tags="teleportable_NOT"
  },
  {
    file="data/entities/buildings/biome_modifiers/drain_pipe.xml",
    image="data/buildings_gfx/drain_pipe.png",
    material="steel",
    name="drain_pipe",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT,destruction_target,glue_NOT"
  },
  {
    file="data/entities/buildings/biome_modifiers/gas_pipe.xml",
    image="data/buildings_gfx/drain_pipe.png",
    material="steel",
    name="gas_pipe",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT,destruction_target,glue_NOT"
  },
  {
    file="data/entities/buildings/biome_modifiers/gas_pipe_floor.xml",
    image="data/buildings_gfx/drain_pipe_floor.png",
    material="steel",
    name="gas_pipe_floor",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT,destruction_target,glue_NOT"
  },
  {
    file="data/entities/buildings/chest_dark.xml",
    image="data/buildings_gfx/chest_dark.png",
    material="rock_box2d_nohit_hard",
    name="chest_dark",
    origin="Vanilla",
    tags="teleportable_NOT,item_physics,chest"
  },
  {
    file="data/entities/buildings/chest_light.xml",
    image="data/buildings_gfx/chest_light.png",
    material="rock_box2d_nohit_hard",
    name="chest_light",
    origin="Vanilla",
    tags="teleportable_NOT,item_physics,chest"
  },
  {
    file="data/entities/buildings/chest_steel.xml",
    image="data/buildings_gfx/chest_steel.png",
    material="steel",
    name="chest_steel",
    origin="Vanilla",
    tags="teleportable_NOT,item_physics,chest"
  },
  {
    file="data/entities/buildings/physics_cocoon.xml",
    image="data/buildings_gfx/cocoon.png",
    material="cocoon_box2d",
    name="physics_cocoon",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/buildings/physics_worm_deflector.xml",
    image="data/props_gfx/worm_deflector.png",
    material="metal_prop",
    name="physics_worm_deflector",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/buildings/physics_worm_deflector_base.xml",
    image="data/props_gfx/worm_deflector_base.png",
    material="metal_prop",
    name="physics_worm_deflector_base",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/buildings/physics_worm_deflector_crystal.xml",
    image="data/props_gfx/worm_deflector_crystal.png",
    material="magic_crystal",
    name="physics_worm_deflector_crystal",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT,worm_crystal"
  },
  {
    file="data/entities/buildings/physics_worm_deflector_lamp.xml",
    image="data/props_gfx/worm_deflector_lamp.png",
    material="metal_prop",
    name="physics_worm_deflector_lamp",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/buildings/statue_hand_1.xml",
    image="data/buildings_gfx/statue_hand_3.png",
    material="rock_box2d_hard",
    name="statue_hand_1",
    origin="Vanilla",
    tags="hittable,effectable_prop,statue_hand_1,statue_hand"
  },
  {
    file="data/entities/buildings/statue_hand_2.xml",
    image="data/buildings_gfx/statue_hand_2.png",
    material="rock_box2d_hard",
    name="statue_hand_2",
    origin="Vanilla",
    tags="hittable,effectable_prop,statue_hand_1,statue_hand,statue_hand_2"
  },
  {
    file="data/entities/buildings/statue_hand_3.xml",
    image="data/buildings_gfx/statue_hand_1.png",
    material="rock_box2d_hard",
    name="statue_hand_3",
    origin="Vanilla",
    tags="hittable,effectable_prop,statue_hand_1,statue_hand,statue_hand_3"
  },
  {
    file="data/entities/items/books/base_book.xml",
    image="data/items_gfx/emerald_tablet.png",
    material="rock_box2d_hard",
    name="base_book",
    origin="Vanilla",
    tags="tablet"
  },
  {
    file="data/entities/items/books/base_forged.xml",
    image="data/items_gfx/laboratory_tablet.png",
    material="rock_box2d_hard",
    name="base_forged",
    origin="Vanilla",
    tags="tablet,forged_tablet"
  },
  {
    file="data/entities/items/books/book_00.xml",
    image="data/items_gfx/emerald_tablet.png",
    material="rock_box2d_hard",
    name="book_00",
    origin="Vanilla",
    tags="tablet,normal_tablet"
  },
  {
    file="data/entities/items/books/book_01.xml",
    image="data/items_gfx/emerald_tablet.png",
    material="rock_box2d_hard",
    name="book_01",
    origin="Vanilla",
    tags="tablet,normal_tablet"
  },
  {
    file="data/entities/items/books/book_02.xml",
    image="data/items_gfx/emerald_tablet.png",
    material="rock_box2d_hard",
    name="book_02",
    origin="Vanilla",
    tags="forgeable,tablet,normal_tablet"
  },
  {
    file="data/entities/items/books/book_03.xml",
    image="data/items_gfx/emerald_tablet.png",
    material="rock_box2d_hard",
    name="book_03",
    origin="Vanilla",
    tags="tablet,normal_tablet"
  },
  {
    file="data/entities/items/books/book_04.xml",
    image="data/items_gfx/emerald_tablet.png",
    material="rock_box2d_hard",
    name="book_04",
    origin="Vanilla",
    tags="forgeable,tablet,normal_tablet"
  },
  {
    file="data/entities/items/books/book_05.xml",
    image="data/items_gfx/emerald_tablet.png",
    material="rock_box2d_hard",
    name="book_05",
    origin="Vanilla",
    tags="forgeable,tablet,normal_tablet"
  },
  {
    file="data/entities/items/books/book_06.xml",
    image="data/items_gfx/emerald_tablet.png",
    material="rock_box2d_hard",
    name="book_06",
    origin="Vanilla",
    tags="forgeable,tablet,normal_tablet"
  },
  {
    file="data/entities/items/books/book_07.xml",
    image="data/items_gfx/emerald_tablet.png",
    material="rock_box2d_hard",
    name="book_07",
    origin="Vanilla",
    tags="forgeable,tablet,normal_tablet"
  },
  {
    file="data/entities/items/books/book_08.xml",
    image="data/items_gfx/emerald_tablet.png",
    material="rock_box2d_hard",
    name="book_08",
    origin="Vanilla",
    tags="forgeable,tablet,normal_tablet"
  },
  {
    file="data/entities/items/books/book_09.xml",
    image="data/items_gfx/emerald_tablet.png",
    material="rock_box2d_hard",
    name="book_09",
    origin="Vanilla",
    tags="forgeable,tablet,normal_tablet"
  },
  {
    file="data/entities/items/books/book_10.xml",
    image="data/items_gfx/emerald_tablet.png",
    material="rock_box2d_hard",
    name="book_10",
    origin="Vanilla",
    tags="forgeable,tablet,normal_tablet"
  },
  {
    file="data/entities/items/books/book_all_spells.xml",
    image="data/items_gfx/laboratory_tablet.png",
    material="rock_box2d_hard",
    name="book_all_spells",
    origin="Vanilla",
    tags="tablet,normal_tablet"
  },
  {
    file="data/entities/items/books/book_barren.xml",
    image="data/items_gfx/book_small.png",
    material="rock_box2d_hard",
    name="book_barren",
    origin="Vanilla",
    tags="scroll,tablet"
  },
  {
    file="data/entities/items/books/book_bunker.xml",
    image="data/items_gfx/book_small.png",
    material="rock_box2d_hard",
    name="book_bunker",
    origin="Vanilla",
    tags="scroll,tablet"
  },
  {
    file="data/entities/items/books/book_corpse.xml",
    image="data/items_gfx/emerald_tablet.png",
    material="rock_box2d_hard",
    name="book_corpse",
    origin="Vanilla",
    tags="tablet,normal_tablet"
  },
  {
    file="data/entities/items/books/book_diamond.xml",
    image="data/items_gfx/book_small.png",
    material="rock_box2d_hard",
    name="book_diamond",
    origin="Vanilla",
    tags="scroll,tablet"
  },
  {
    file="data/entities/items/books/book_essences.xml",
    image="data/items_gfx/book_small.png",
    material="rock_box2d_hard",
    name="book_essences",
    origin="Vanilla",
    tags="scroll,tablet"
  },
  {
    file="data/entities/items/books/book_hint.xml",
    image="data/items_gfx/book_small.png",
    material="rock_box2d_hard",
    name="book_hint",
    origin="Vanilla",
    tags="scroll,tablet"
  },
  {
    file="data/entities/items/books/book_mestari.xml",
    image="data/items_gfx/book_small.png",
    material="rock_box2d_hard",
    name="book_mestari",
    origin="Vanilla",
    tags="scroll,tablet"
  },
  {
    file="data/entities/items/books/book_moon.xml",
    image="data/items_gfx/book_small.png",
    material="rock_box2d_hard",
    name="book_moon",
    origin="Vanilla",
    tags="scroll,tablet"
  },
  {
    file="data/entities/items/books/book_music_a.xml",
    image="data/items_gfx/book_small.png",
    material="rock_box2d_hard",
    name="book_music_a",
    origin="Vanilla",
    tags="scroll,tablet"
  },
  {
    file="data/entities/items/books/book_music_b.xml",
    image="data/items_gfx/book_small.png",
    material="rock_box2d_hard",
    name="book_music_b",
    origin="Vanilla",
    tags="scroll,tablet"
  },
  {
    file="data/entities/items/books/book_music_c.xml",
    image="data/items_gfx/book_small.png",
    material="rock_box2d_hard",
    name="book_music_c",
    origin="Vanilla",
    tags="scroll,tablet"
  },
  {
    file="data/entities/items/books/book_robot.xml",
    image="data/items_gfx/book_small.png",
    material="rock_box2d_hard",
    name="book_robot",
    origin="Vanilla",
    tags="scroll,tablet"
  },
  {
    file="data/entities/items/books/book_s_a.xml",
    image="data/items_gfx/book_s_small.png",
    material="rock_box2d_hard",
    name="book_s_a",
    origin="Vanilla",
    tags="scroll,tablet"
  },
  {
    file="data/entities/items/books/book_s_b.xml",
    image="data/items_gfx/book_s_small.png",
    material="rock_box2d_hard",
    name="book_s_b",
    origin="Vanilla",
    tags="scroll,tablet"
  },
  {
    file="data/entities/items/books/book_s_c.xml",
    image="data/items_gfx/book_s_small.png",
    material="rock_box2d_hard",
    name="book_s_c",
    origin="Vanilla",
    tags="scroll,tablet"
  },
  {
    file="data/entities/items/books/book_s_d.xml",
    image="data/items_gfx/book_s_small.png",
    material="rock_box2d_hard",
    name="book_s_d",
    origin="Vanilla",
    tags="scroll,tablet"
  },
  {
    file="data/entities/items/books/book_s_e.xml",
    image="data/items_gfx/book_s_small.png",
    material="rock_box2d_hard",
    name="book_s_e",
    origin="Vanilla",
    tags="scroll,tablet"
  },
  {
    file="data/entities/items/books/book_tree.xml",
    image="data/items_gfx/emerald_tablet.png",
    material="rock_box2d_hard",
    name="book_tree",
    origin="Vanilla",
    tags="tablet,normal_tablet"
  },
  {
    file="data/entities/items/easter/beer_bottle.xml",
    image="data/items_gfx/beer_bottle.png",
    material="glass_box2d",
    name="beer_bottle",
    origin="Vanilla",
    tags="hittable,teleportable_NOT"
  },
  {
    file="data/entities/items/easter/druidsoccer_ball.xml",
    image="data/items_gfx/easter/druidsoccer_ball.png",
    material="rock_box2d",
    name="druidsoccer_ball",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/items/easter/minit_watering.xml",
    image="data/items_gfx/minit_watering_can.png",
    material="steel",
    name="minit_watering",
    origin="Vanilla",
    tags="hittable,teleportable_NOT"
  },
  {
    file="data/entities/items/pickup/beamstone.xml",
    image="data/items_gfx/beamstone.png",
    material="gem_box2d_opal",
    name="beamstone",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup"
  },
  {
    file="data/entities/items/pickup/bloodmoney_10.xml",
    image="data/items_gfx/goldnugget_6px.png",
    material="bloodgold_box2d",
    name="bloodmoney_10",
    origin="Vanilla",
    tags="item_physics,gold_nugget"
  },
  {
    file="data/entities/items/pickup/bloodmoney_1000.xml",
    image="data/items_gfx/goldnugget_20px.png",
    material="bloodgold_box2d",
    name="bloodmoney_1000",
    origin="Vanilla",
    tags="item_physics,gold_nugget"
  },
  {
    file="data/entities/items/pickup/bloodmoney_10000.xml",
    image="data/items_gfx/easter/golden_idol.png",
    material="bloodgold_box2d",
    name="bloodmoney_10000",
    origin="Vanilla",
    tags="item_physics,gold_nugget"
  },
  {
    file="data/entities/items/pickup/bloodmoney_200.xml",
    image="data/items_gfx/goldnugget_12px.png",
    material="bloodgold_box2d",
    name="bloodmoney_200",
    origin="Vanilla",
    tags="item_physics,gold_nugget"
  },
  {
    file="data/entities/items/pickup/bloodmoney_200000.xml",
    image="data/items_gfx/easter/golden_idol_big.png",
    material="bloodgold_box2d",
    name="bloodmoney_200000",
    origin="Vanilla",
    tags="item_physics,gold_nugget"
  },
  {
    file="data/entities/items/pickup/bloodmoney_50.xml",
    image="data/items_gfx/goldnugget_9px.png",
    material="bloodgold_box2d",
    name="bloodmoney_50",
    origin="Vanilla",
    tags="item_physics,gold_nugget"
  },
  {
    file="data/entities/items/pickup/brimstone.xml",
    image="data/items_gfx/brimstone.png",
    material="sulphur_box2d",
    name="brimstone",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,brimstone"
  },
  {
    file="data/entities/items/pickup/broken_wand.xml",
    image="data/items_gfx/broken_wand.png",
    material="item_box2d",
    name="broken_wand",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,forgeable,broken_wand"
  },
  {
    file="data/entities/items/pickup/chest_leggy.xml",
    image="data/buildings_gfx/chest_random.png",
    material="wood_prop",
    name="chest_leggy",
    origin="Vanilla",
    tags="teleportable_NOT,item_physics,item_pickup,effectable_prop"
  },
  {
    file="data/entities/items/pickup/chest_random.xml",
    image="data/buildings_gfx/chest_random.png",
    material="wood_prop",
    name="chest_random",
    origin="Vanilla",
    tags="teleportable_NOT,item_physics,item_pickup,chest,effectable_prop"
  },
  {
    file="data/entities/items/pickup/chest_random_super.xml",
    image="data/buildings_gfx/chest_random_super.png",
    material="wood_prop",
    name="chest_random_super",
    origin="Vanilla",
    tags="teleportable_NOT,item_physics,item_pickup,chest,effectable_prop"
  },
  {
    file="data/entities/items/pickup/egg_fire.xml",
    image="data/items_gfx/egg_red.png",
    material="bone_box2d",
    name="egg_fire",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,egg_item"
  },
  {
    file="data/entities/items/pickup/egg_hollow.xml",
    image="data/items_gfx/egg_slime.png",
    material="bone_box2d",
    name="egg_hollow",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,egg_item"
  },
  {
    file="data/entities/items/pickup/egg_monster.xml",
    image="data/items_gfx/egg.png",
    material="bone_box2d",
    name="egg_monster",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,egg_item"
  },
  {
    file="data/entities/items/pickup/egg_purple.xml",
    image="data/items_gfx/egg_purple.png",
    material="bone_box2d",
    name="egg_purple",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,egg_item"
  },
  {
    file="data/entities/items/pickup/egg_red.xml",
    image="data/items_gfx/egg_red.png",
    material="bone_box2d",
    name="egg_red",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,egg_item"
  },
  {
    file="data/entities/items/pickup/egg_slime.xml",
    image="data/items_gfx/egg_slime.png",
    material="bone_box2d",
    name="egg_slime",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,egg_item"
  },
  {
    file="data/entities/items/pickup/egg_spiders.xml",
    image="data/items_gfx/egg_purple.png",
    material="bone_box2d",
    name="egg_spiders",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,egg_item"
  },
  {
    file="data/entities/items/pickup/egg_worm.xml",
    image="data/items_gfx/egg_worm.png",
    material="bone_box2d",
    name="egg_worm",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,egg_item"
  },
  {
    file="data/entities/items/pickup/evil_eye.xml",
    image="data/items_gfx/evil_eye.png",
    material="item_box2d_meat",
    name="evil_eye",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,evil_eye"
  },
  {
    file="data/entities/items/pickup/goldnugget.xml",
    image="data/items_gfx/goldnugget_01.png",
    material="gold_box2d",
    name="goldnugget",
    origin="Vanilla",
    tags="item_physics,gold_nugget"
  },
  {
    file="data/entities/items/pickup/goldnugget_10.xml",
    image="data/items_gfx/goldnugget_6px.png",
    material="gold_box2d",
    name="goldnugget_10",
    origin="Vanilla",
    tags="item_physics,gold_nugget"
  },
  {
    file="data/entities/items/pickup/goldnugget_1000.xml",
    image="data/items_gfx/goldnugget_20px.png",
    material="gold_box2d",
    name="goldnugget_1000",
    origin="Vanilla",
    tags="item_physics,gold_nugget"
  },
  {
    file="data/entities/items/pickup/goldnugget_10000.xml",
    image="data/items_gfx/easter/golden_idol.png",
    material="metal_prop",
    name="goldnugget_10000",
    origin="Vanilla",
    tags="item_physics,gold_nugget"
  },
  {
    file="data/entities/items/pickup/goldnugget_200.xml",
    image="data/items_gfx/goldnugget_12px.png",
    material="gold_box2d",
    name="goldnugget_200",
    origin="Vanilla",
    tags="item_physics,gold_nugget"
  },
  {
    file="data/entities/items/pickup/goldnugget_200000.xml",
    image="data/items_gfx/easter/golden_idol_big.png",
    material="gold_box2d",
    name="goldnugget_200000",
    origin="Vanilla",
    tags="item_physics,gold_nugget"
  },
  {
    file="data/entities/items/pickup/goldnugget_50.xml",
    image="data/items_gfx/goldnugget_9px.png",
    material="gold_box2d",
    name="goldnugget_50",
    origin="Vanilla",
    tags="item_physics,gold_nugget"
  },
  {
    file="data/entities/items/pickup/gourd.xml",
    image="data/items_gfx/gourd.png",
    material="meat_fruit",
    name="gourd",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,gourd"
  },
  {
    file="data/entities/items/pickup/jar.xml",
    image="data/items_gfx/jar_normals.png",
    material="potion_glass_box2d",
    name="jar",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,potion"
  },
  {
    file="data/entities/items/pickup/jar_of_urine.xml",
    image="data/items_gfx/jar_normals.png",
    material="potion_glass_box2d",
    name="jar_of_urine",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,potion"
  },
  {
    file="data/entities/items/pickup/moon.xml",
    image="data/items_gfx/moon.png",
    material="item_box2d",
    name="moon",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_pickup,moon_energy"
  },
  {
    file="data/entities/items/pickup/musicstone.xml",
    image="data/items_gfx/musicstone.png",
    material="gem_box2d_turquoise",
    name="musicstone",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,moon_energy"
  },
  {
    file="data/entities/items/pickup/physics_die.xml",
    image="data/props_gfx/die.png",
    material="rock_box2d_hard",
    name="physics_die",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup"
  },
  {
    file="data/entities/items/pickup/physics_gold_orb.xml",
    image="data/items_gfx/orb.png",
    material="metal_hard",
    name="physics_gold_orb",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup"
  },
  {
    file="data/entities/items/pickup/physics_gold_orb_greed.xml",
    image="data/items_gfx/orb_greed.png",
    material="metal_hard",
    name="physics_gold_orb_greed",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup"
  },
  {
    file="data/entities/items/pickup/physics_greed_die.xml",
    image="data/props_gfx/greed_die.png",
    material="rock_box2d_hard",
    name="physics_greed_die",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup"
  },
  {
    file="data/entities/items/pickup/poopstone.xml",
    image="data/items_gfx/kakke.png",
    material="poop_box2d_hard",
    name="poopstone",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,poopstone"
  },
  {
    file="data/entities/items/pickup/potion.xml",
    image="data/items_gfx/potion_normals.png",
    material="potion_glass_box2d",
    name="potion",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,potion"
  },
  {
    file="data/entities/items/pickup/potion_aggressive.xml",
    image="data/items_gfx/potion_alchemist_normals.png",
    material="potion_glass_box2d",
    name="potion_aggressive",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,potion,projectile_item"
  },
  {
    file="data/entities/items/pickup/potion_alcohol.xml",
    image="data/items_gfx/potion_normals.png",
    material="potion_glass_box2d",
    name="potion_alcohol",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,potion"
  },
  {
    file="data/entities/items/pickup/potion_beer.xml",
    image="data/items_gfx/potion_normals.png",
    material="potion_glass_box2d",
    name="potion_beer",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,potion"
  },
  {
    file="data/entities/items/pickup/potion_empty.xml",
    image="data/items_gfx/potion_normals.png",
    material="potion_glass_box2d",
    name="potion_empty",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,potion"
  },
  {
    file="data/entities/items/pickup/potion_milk.xml",
    image="data/items_gfx/potion_normals.png",
    material="potion_glass_box2d",
    name="potion_milk",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,potion"
  },
  {
    file="data/entities/items/pickup/potion_mimic.xml",
    image="data/items_gfx/potion_normals.png",
    material="potion_glass_box2d",
    name="potion_mimic",
    origin="Vanilla",
    tags="teleportable_NOT,item_physics,item_pickup,effectable_prop"
  },
  {
    file="data/entities/items/pickup/potion_porridge.xml",
    image="data/items_gfx/potion_normals.png",
    material="potion_glass_box2d",
    name="potion_porridge",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,potion"
  },
  {
    file="data/entities/items/pickup/potion_random_material.xml",
    image="data/items_gfx/potion_normals.png",
    material="potion_glass_box2d",
    name="potion_random_material",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,potion"
  },
  {
    file="data/entities/items/pickup/potion_secret.xml",
    image="data/items_gfx/potion_normals.png",
    material="potion_glass_box2d",
    name="potion_secret",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,potion"
  },
  {
    file="data/entities/items/pickup/potion_slime.xml",
    image="data/items_gfx/potion_normals.png",
    material="potion_glass_box2d",
    name="potion_slime",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,potion"
  },
  {
    file="data/entities/items/pickup/potion_starting.xml",
    image="data/items_gfx/potion_normals.png",
    material="potion_glass_box2d",
    name="potion_starting",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,potion"
  },
  {
    file="data/entities/items/pickup/potion_vomit.xml",
    image="data/items_gfx/potion_normals.png",
    material="potion_glass_box2d",
    name="potion_vomit",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,potion"
  },
  {
    file="data/entities/items/pickup/potion_water.xml",
    image="data/items_gfx/potion_normals.png",
    material="potion_glass_box2d",
    name="potion_water",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,potion"
  },
  {
    file="data/entities/items/pickup/powder_stash.xml",
    image="data/items_gfx/material_pouch.png",
    material="cloth_box2d",
    name="powder_stash",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,powder_stash"
  },
  {
    file="data/entities/items/pickup/runestones/runestone_base.xml",
    image="data/items_gfx/runestones/runestone_slow.png",
    material="rock_box2d_hard",
    name="runestone_base",
    origin="Vanilla",
    tags="teleportable_NOT,item_physics,item_pickup"
  },
  {
    file="data/entities/items/pickup/runestones/runestone_disc.xml",
    image="data/items_gfx/runestones/runestone_disc.png",
    material="rock_box2d_hard",
    name="runestone_disc",
    origin="Vanilla",
    tags="teleportable_NOT,item_physics,item_pickup"
  },
  {
    file="data/entities/items/pickup/runestones/runestone_fireball.xml",
    image="data/items_gfx/runestones/runestone_fireball.png",
    material="rock_box2d_hard",
    name="runestone_fireball",
    origin="Vanilla",
    tags="teleportable_NOT,item_physics,item_pickup"
  },
  {
    file="data/entities/items/pickup/runestones/runestone_laser.xml",
    image="data/items_gfx/runestones/runestone_laser.png",
    material="rock_box2d_hard",
    name="runestone_laser",
    origin="Vanilla",
    tags="teleportable_NOT,item_physics,item_pickup"
  },
  {
    file="data/entities/items/pickup/runestones/runestone_lava.xml",
    image="data/items_gfx/runestones/runestone_lava.png",
    material="rock_box2d_hard",
    name="runestone_lava",
    origin="Vanilla",
    tags="teleportable_NOT,item_physics,item_pickup"
  },
  {
    file="data/entities/items/pickup/runestones/runestone_metal.xml",
    image="data/items_gfx/runestones/runestone_metal.png",
    material="rock_box2d_hard",
    name="runestone_metal",
    origin="Vanilla",
    tags="teleportable_NOT,item_physics,item_pickup"
  },
  {
    file="data/entities/items/pickup/runestones/runestone_null.xml",
    image="data/items_gfx/runestones/runestone_null.png",
    material="rock_box2d_hard",
    name="runestone_null",
    origin="Vanilla",
    tags="teleportable_NOT,item_physics,item_pickup"
  },
  {
    file="data/entities/items/pickup/runestones/runestone_slow.xml",
    image="data/items_gfx/runestones/runestone_slow.png",
    material="rock_box2d_hard",
    name="runestone_slow",
    origin="Vanilla",
    tags="teleportable_NOT,item_physics,item_pickup"
  },
  {
    file="data/entities/items/pickup/safe_haven.xml",
    image="data/items_gfx/safe_haven.png",
    material="item_box2d_glass",
    name="safe_haven",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics"
  },
  {
    file="data/entities/items/pickup/stonestone.xml",
    image="data/items_gfx/stonestone.png",
    material="rock_box2d_hard",
    name="stonestone",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,stonestone"
  },
  {
    file="data/entities/items/pickup/summon_portal_broken.xml",
    image="data/items_gfx/broken_spell.png",
    material="item_box2d",
    name="summon_portal_broken",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,forgeable,card_summon_portal_broken"
  },
  {
    file="data/entities/items/pickup/sun/newsun.xml",
    name="newsun",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,seed_e"
  },
  {
    file="data/entities/items/pickup/sun/newsun_dark.xml",
    name="newsun_dark",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,seed_f"
  },
  {
    file="data/entities/items/pickup/sun/sunbaby.xml",
    name="sunbaby",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,seed_d"
  },
  {
    file="data/entities/items/pickup/sun/sunegg.xml",
    image="data/items_gfx/normals_orb_56_noise.png",
    material="gem_box2d_yellow_sun",
    name="sunegg",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,seed_c"
  },
  {
    file="data/entities/items/pickup/sun/sunseed.xml",
    image="data/items_gfx/goldnugget_01.png",
    material="gem_box2d_white",
    name="sunseed",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,seed_a"
  },
  {
    file="data/entities/items/pickup/sun/sunstone.xml",
    image="data/items_gfx/goldnugget_9px.png",
    material="gem_box2d_red_float",
    name="sunstone",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,seed_b"
  },
  {
    file="data/entities/items/pickup/test/pouch.xml",
    image="data/items_gfx/potion_normals.png",
    material="potion_glass_box2d",
    name="pouch",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics"
  },
  {
    file="data/entities/items/pickup/test/pouch_static.xml",
    image="data/items_gfx/potion_normals.png",
    material="potion_glass_box2d",
    name="pouch_static",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics"
  },
  {
    file="data/entities/items/pickup/thunderstone.xml",
    image="data/items_gfx/smallgem_03.png",
    material="gem_box2d",
    name="thunderstone",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,thunderstone"
  },
  {
    file="data/entities/items/pickup/utility_box.xml",
    image="data/items_gfx/utility_box.png",
    material="metal_prop",
    name="utility_box",
    origin="Vanilla",
    tags="teleportable_NOT,item_physics,item_pickup,effectable_prop,utility_box"
  },
  {
    file="data/entities/items/pickup/wandstone.xml",
    image="data/items_gfx/goldnugget_01.png",
    material="gem_box2d_turquoise",
    name="wandstone",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup"
  },
  {
    file="data/entities/items/pickup/waterstone.xml",
    image="data/items_gfx/waterstone.png",
    material="rock_box2d_hard",
    name="waterstone",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,waterstone"
  },
  {
    file="data/entities/items/shop_potion.xml",
    image="data/items_gfx/potion_normals.png",
    material="potion_glass_box2d",
    name="shop_potion",
    origin="Vanilla",
    tags="hittable,teleportable_NOT,item_physics,item_pickup,potion,item,glue_NOT,item_shop"
  },
  {
    file="data/entities/misc/chest_random_dummy.xml",
    image="data/buildings_gfx/chest_random.png",
    material="wood_prop",
    name="chest_random_dummy",
    origin="Vanilla",
    tags="teleportable_NOT"
  },
  {
    file="data/entities/misc/greed_curse/greed_crystal.xml",
    image="data/props_gfx/worm_deflector_crystal.png",
    material="magic_crystal_green",
    name="greed_crystal",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT,greed_crystal"
  },
  {
    file="data/entities/props/_test_physics_heavy.xml",
    image="data/temp/_test_base.png",
    material="aluminium",
    name="_test_physics_heavy",
    origin="Vanilla",
    tags="hittable"
  },
  {
    file="data/entities/props/_test_physics_light.xml",
    image="data/props_gfx/torch_hang_base.png",
    material="aluminium",
    name="_test_physics_light",
    origin="Vanilla",
    tags="hittable"
  },
  {
    file="data/entities/props/altar_torch.xml",
    image="data/props_gfx/altar_torch.png",
    material="templebrick_static",
    name="altar_torch",
    origin="Vanilla",
    tags="vegetation,altar_torch"
  },
  {
    file="data/entities/props/altar_torch_old.xml",
    image="data/props_gfx/altar_torch.png",
    material="templebrick_static",
    name="altar_torch_old",
    origin="Vanilla",
    tags="vegetation,altar_torch"
  },
  {
    file="data/entities/props/base_coalmine_structure.xml",
    image="data/props_gfx/coalmine_structure_background_02.png",
    material="wood_loose",
    name="base_coalmine_structure",
    origin="Vanilla",
    tags="vegetation,pixelsprite"
  },
  {
    file="data/entities/props/boss_arena_statue_1.xml",
    image="data/biome_impl/boss_arena_statue_1.png",
    material="rock_loose",
    name="boss_arena_statue_1",
    origin="Vanilla",
    tags="vegetation,pixelsprite"
  },
  {
    file="data/entities/props/boss_arena_statue_2.xml",
    image="data/biome_impl/boss_arena_statue_2.png",
    material="rock_loose",
    name="boss_arena_statue_2",
    origin="Vanilla",
    tags="vegetation,pixelsprite"
  },
  {
    file="data/entities/props/boss_arena_statue_3.xml",
    image="data/biome_impl/boss_arena_statue_3.png",
    material="rock_loose",
    name="boss_arena_statue_3",
    origin="Vanilla",
    tags="vegetation,pixelsprite"
  },
  {
    file="data/entities/props/boss_arena_statue_4.xml",
    image="data/biome_impl/boss_arena_statue_4.png",
    material="rock_loose",
    name="boss_arena_statue_4",
    origin="Vanilla",
    tags="vegetation,pixelsprite"
  },
  {
    file="data/entities/props/coalmine_i_structure_01.xml",
    image="data/props_gfx/coalmine_i_structure_background_01.png",
    material="wood_loose",
    name="coalmine_i_structure_01",
    origin="Vanilla",
    tags="vegetation,pixelsprite"
  },
  {
    file="data/entities/props/coalmine_i_structure_02.xml",
    image="data/props_gfx/coalmine_i_structure_background_02.png",
    material="wood_loose",
    name="coalmine_i_structure_02",
    origin="Vanilla",
    tags="vegetation,pixelsprite"
  },
  {
    file="data/entities/props/coalmine_large_structure_01.xml",
    image="data/props_gfx/coalmine_large_structure_background_01.png",
    material="wood_loose",
    name="coalmine_large_structure_01",
    origin="Vanilla",
    tags="vegetation,pixelsprite"
  },
  {
    file="data/entities/props/coalmine_large_structure_02.xml",
    image="data/props_gfx/coalmine_large_structure_background_02.png",
    material="wood_loose",
    name="coalmine_large_structure_02",
    origin="Vanilla",
    tags="vegetation,pixelsprite"
  },
  {
    file="data/entities/props/coalmine_structure_01.xml",
    image="data/props_gfx/coalmine_structure_background_01.png",
    material="wood_loose",
    name="coalmine_structure_01",
    origin="Vanilla",
    tags="vegetation,pixelsprite"
  },
  {
    file="data/entities/props/coalmine_structure_02.xml",
    image="data/props_gfx/coalmine_structure_background_02.png",
    material="wood_loose",
    name="coalmine_structure_02",
    origin="Vanilla",
    tags="vegetation,pixelsprite"
  },
  {
    file="data/entities/props/crystal_green.xml",
    image="data/props_gfx/crystal_green.png",
    material="crystal_solid",
    name="crystal_green",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/crystal_pink.xml",
    image="data/props_gfx/crystal_pink.png",
    material="crystal_solid",
    name="crystal_pink",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/crystal_red.xml",
    image="data/props_gfx/crystal_red.png",
    material="crystal_solid",
    name="crystal_red",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/excavationsite_machine_3b.xml",
    image="data/props_gfx/excavationsite_machine_3b.png",
    material="wood_player_b2",
    name="excavationsite_machine_3b",
    origin="Vanilla",
    tags=""
  },
  {
    file="data/entities/props/excavationsite_machine_3c.xml",
    image="data/props_gfx/excavationsite_machine_3c.png",
    material="wood_player_b2",
    name="excavationsite_machine_3c",
    origin="Vanilla",
    tags=""
  },
  {
    file="data/entities/props/forcefield_generator.xml",
    image="data/props_gfx/forcefield_generator.png",
    material="steel",
    name="forcefield_generator",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/furniture_bed.xml",
    image="data/props_gfx/furniture_bed.png",
    material="wood_prop",
    name="furniture_bed",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/furniture_bunk.xml",
    image="data/props_gfx/furniture_bunk_bed.png",
    material="metal_prop",
    name="furniture_bunk",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/furniture_castle_chair.xml",
    image="data/props_gfx/furniture_castle_chair.png",
    material="rock_box2d",
    name="furniture_castle_chair",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/furniture_castle_divan.xml",
    image="data/props_gfx/furniture_castle_divan.png",
    material="rock_box2d",
    name="furniture_castle_divan",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/furniture_castle_statue.xml",
    image="data/props_gfx/furniture_castle_statue.png",
    material="rock_box2d",
    name="furniture_castle_statue",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/furniture_castle_table.xml",
    image="data/props_gfx/furniture_castle_table.png",
    material="rock_box2d",
    name="furniture_castle_table",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/furniture_castle_wardrobe.xml",
    image="data/props_gfx/furniture_castle_wardrobe.png",
    material="rock_box2d",
    name="furniture_castle_wardrobe",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/furniture_cryopod.xml",
    image="data/props_gfx/furniture_cryopod.png",
    material="metal_prop_loose",
    name="furniture_cryopod",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/furniture_dresser.xml",
    image="data/props_gfx/furniture_dresser.png",
    material="wood_prop",
    name="furniture_dresser",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/furniture_footlocker.xml",
    image="data/props_gfx/furniture_footlocker.png",
    material="metal_prop",
    name="furniture_footlocker",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/furniture_locker.xml",
    image="data/props_gfx/furniture_locker_frame.png",
    material="metal_prop_loose",
    name="furniture_locker",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/furniture_rocking_chair.xml",
    image="data/props_gfx/furniture_rocking_chair.png",
    material="wood_prop",
    name="furniture_rocking_chair",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/furniture_stool.xml",
    image="data/props_gfx/furniture_stool.png",
    material="metal_prop",
    name="furniture_stool",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/furniture_table.xml",
    image="data/props_gfx/furniture_table_top.png",
    material="metal_prop",
    name="furniture_table",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/furniture_tombstone_01.xml",
    image="data/props_gfx/furniture_tombstone_01.png",
    material="rock_box2d",
    name="furniture_tombstone_01",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/furniture_tombstone_02.xml",
    image="data/props_gfx/furniture_tombstone_02.png",
    material="rock_box2d",
    name="furniture_tombstone_02",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/furniture_tombstone_03.xml",
    image="data/props_gfx/furniture_tombstone_03.png",
    material="rock_box2d",
    name="furniture_tombstone_03",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/furniture_wardrobe.xml",
    image="data/props_gfx/furniture_wardrobe.png",
    material="wood_prop",
    name="furniture_wardrobe",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/furniture_wood_chair.xml",
    image="data/props_gfx/furniture_wood_chair.png",
    material="wood_prop",
    name="furniture_wood_chair",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/furniture_wood_table.xml",
    image="data/props_gfx/furniture_wood_table.png",
    material="wood_prop",
    name="furniture_wood_table",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/ladder_long.xml",
    image="data/props_gfx/ladder_long.png",
    material="wood_loose",
    name="ladder_long",
    origin="Vanilla",
    tags="prop,pixelsprite"
  },
  {
    file="data/entities/props/mountain_left_entrance_grass.xml",
    image="data/biome_impl/mountain/left_entrance_grass.png",
    material="wood_loose",
    name="mountain_left_entrance_grass",
    origin="Vanilla",
    tags="vegetation,pixelsprite"
  },
  {
    file="data/entities/props/music_machines/base_music_machine.xml",
    image="data/props_gfx/music_machine.png",
    material="metal_prop_low_restitution",
    name="base_music_machine",
    origin="Vanilla",
    tags="mortal"
  },
  {
    file="data/entities/props/music_machines/music_machine_00.xml",
    image="data/props_gfx/music_machine.png",
    material="metal_prop_low_restitution",
    name="music_machine_00",
    origin="Vanilla",
    tags="mortal,musicmachine,musicmachine1"
  },
  {
    file="data/entities/props/music_machines/music_machine_01.xml",
    image="data/props_gfx/music_machine.png",
    material="metal_prop_low_restitution",
    name="music_machine_01",
    origin="Vanilla",
    tags="mortal,musicmachine,musicmachine2"
  },
  {
    file="data/entities/props/music_machines/music_machine_02.xml",
    image="data/props_gfx/music_machine.png",
    material="metal_prop_low_restitution",
    name="music_machine_02",
    origin="Vanilla",
    tags="mortal,musicmachine,musicmachine3"
  },
  {
    file="data/entities/props/music_machines/music_machine_03.xml",
    image="data/props_gfx/music_machine.png",
    material="metal_prop_low_restitution",
    name="music_machine_03",
    origin="Vanilla",
    tags="mortal,musicmachine,musicmachine4"
  },
  {
    file="data/entities/props/overworld/banner_01.xml",
    image="data/props_gfx/overworld/pole_01.png",
    material="wood_prop_noplayerhit",
    name="banner_01",
    origin="Vanilla",
    tags=""
  },
  {
    file="data/entities/props/overworld/banner_02.xml",
    image="data/props_gfx/overworld/pole_02.png",
    material="wood_prop_noplayerhit",
    name="banner_02",
    origin="Vanilla",
    tags=""
  },
  {
    file="data/entities/props/overworld/banner_03.xml",
    image="data/props_gfx/overworld/pole_02.png",
    material="wood_prop_noplayerhit",
    name="banner_03",
    origin="Vanilla",
    tags=""
  },
  {
    file="data/entities/props/physics/bridge_spawner.xml",
    name="bridge_spawner",
    origin="Vanilla",
    tags="trailer"
  },
  {
    file="data/entities/props/physics/chain_torch.xml",
    image="data/props_gfx/torch_hang_chain_ceiling.png",
    material="metal_chain_nohit",
    name="chain_torch",
    origin="Vanilla",
    tags="hittable"
  },
  {
    file="data/entities/props/physics/chain_torch_blue.xml",
    image="data/props_gfx/torch_hang_chain_ceiling.png",
    material="metal_chain_nohit",
    name="chain_torch_blue",
    origin="Vanilla",
    tags="hittable"
  },
  {
    file="data/entities/props/physics/chain_torch_ghostly.xml",
    image="data/props_gfx/torch_hang_chain_ceiling.png",
    material="metal_chain_nohit",
    name="chain_torch_ghostly",
    origin="Vanilla",
    tags="hittable"
  },
  {
    file="data/entities/props/physics/lantern_small.xml",
    image="data/props_gfx/lantern_small.png",
    material="glass_box2d",
    name="lantern_small",
    origin="Vanilla",
    tags="mortal,prop,prop_physics"
  },
  {
    file="data/entities/props/physics/minecart.xml",
    image="data/props_gfx/minecart.png",
    material="metal_rust",
    name="minecart",
    origin="Vanilla",
    tags=""
  },
  {
    file="data/entities/props/physics/temple_lantern.xml",
    image="data/props_gfx/temple_lantern_01.png",
    material="metal_nohit",
    name="temple_lantern",
    origin="Vanilla",
    tags="prop,prop_physics,hittable"
  },
  {
    file="data/entities/props/physics/trap_circle_acid.xml",
    image="data/props_gfx/trap_acid.png",
    material="steel",
    name="trap_circle_acid",
    origin="Vanilla",
    tags="mortal,prop,prop_physics"
  },
  {
    file="data/entities/props/physics/trap_electricity.xml",
    image="data/props_gfx/trap_electricity.png",
    material="steel",
    name="trap_electricity",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics/trap_electricity_enabled.xml",
    image="data/props_gfx/trap_electricity.png",
    material="steel",
    name="trap_electricity_enabled",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics/trap_electricity_suspended.xml",
    image="data/props_gfx/trap_electricity.png",
    material="steel",
    name="trap_electricity_suspended",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics/trap_ignite.xml",
    image="data/props_gfx/trap_ignite_a.png",
    material="steel",
    name="trap_ignite",
    origin="Vanilla",
    tags="mortal,prop,prop_physics"
  },
  {
    file="data/entities/props/physics/trap_ignite_enabled.xml",
    image="data/props_gfx/trap_ignite_a.png",
    material="steel",
    name="trap_ignite_enabled",
    origin="Vanilla",
    tags="mortal,prop,prop_physics"
  },
  {
    file="data/entities/props/physics/trap_laser.xml",
    image="data/props_gfx/trap_laser.png",
    material="steel",
    name="trap_laser",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics/trap_laser_enabled.xml",
    image="data/props_gfx/trap_laser.png",
    material="steel",
    name="trap_laser_enabled",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics/trap_laser_enabled_left.xml",
    image="data/props_gfx/trap_laser_left.png",
    material="steel",
    name="trap_laser_enabled_left",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics/trap_laser_toggling.xml",
    image="data/props_gfx/trap_laser_small.png",
    material="steel",
    name="trap_laser_toggling",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics/trap_laser_toggling_left.xml",
    image="data/props_gfx/trap_laser_small_b.png",
    material="steel",
    name="trap_laser_toggling_left",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_barrel_burning.xml",
    image="data/props_gfx/barrel_burning.png",
    material="metal_rust_barrel",
    name="physics_barrel_burning",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_barrel_oil.xml",
    image="data/props_gfx/barrel_unstable.png",
    material="metal_rust_barrel",
    name="physics_barrel_oil",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_barrel_radioactive.xml",
    image="data/props_gfx/barrel_radioactive.png",
    material="metal_rust_barrel",
    name="physics_barrel_radioactive",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_barrel_water.xml",
    image="data/props_gfx/barrel_water.png",
    material="wood_prop",
    name="physics_barrel_water",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_bed.xml",
    image="data/props_gfx/bed.png",
    material="wood_prop",
    name="physics_bed",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_bone_01.xml",
    image="data/props_gfx/bone_01.png",
    material="bone_box2d",
    name="physics_bone_01",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_bone_02.xml",
    image="data/props_gfx/bone_02.png",
    material="bone_box2d",
    name="physics_bone_02",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_bone_03.xml",
    image="data/props_gfx/bone_03.png",
    material="bone_box2d",
    name="physics_bone_03",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_bone_04.xml",
    image="data/props_gfx/bone_04.png",
    material="bone_box2d",
    name="physics_bone_04",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_bone_05.xml",
    image="data/props_gfx/bone_05.png",
    material="bone_box2d",
    name="physics_bone_05",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_bone_06.xml",
    image="data/props_gfx/bone_06.png",
    material="bone_box2d",
    name="physics_bone_06",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_bottle_blue.xml",
    image="data/props_gfx/bottle_blue.png",
    material="plastic_prop",
    name="physics_bottle_blue",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_bottle_green.xml",
    image="data/props_gfx/bottle_green.png",
    material="plastic_prop",
    name="physics_bottle_green",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_bottle_red.xml",
    image="data/props_gfx/bottle_red.png",
    material="plastic_prop",
    name="physics_bottle_red",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_bottle_yellow.xml",
    image="data/props_gfx/bottle_yellow.png",
    material="plastic_prop",
    name="physics_bottle_yellow",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_box_explosive.xml",
    image="data/props_gfx/tnt.png",
    material="wood_prop",
    name="physics_box_explosive",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_box_harmless.xml",
    image="data/props_gfx/box.png",
    material="wood_prop",
    name="physics_box_harmless",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_box_harmless_small.xml",
    image="data/props_gfx/box_small.png",
    material="wood_prop",
    name="physics_box_harmless_small",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_brewing_stand.xml",
    image="data/props_gfx/brewing_stand.png",
    material="wood_prop",
    name="physics_brewing_stand",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_bucket.xml",
    image="data/props_gfx/bucket.png",
    material="wood_prop",
    name="physics_bucket",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_campfire.xml",
    image="data/props_gfx/campfire.png",
    material="wood_prop_durable",
    name="physics_campfire",
    origin="Vanilla",
    tags=""
  },
  {
    file="data/entities/props/physics_candle_1.xml",
    image="data/props_gfx/physics_candle_1.png",
    material="wax_b2",
    name="physics_candle_1",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_candle_2.xml",
    image="data/props_gfx/physics_candle_2.png",
    material="wax_b2",
    name="physics_candle_2",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_candle_3.xml",
    image="data/props_gfx/physics_candle_3.png",
    material="wax_b2",
    name="physics_candle_3",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_cart.xml",
    image="data/props_gfx/cart_top.png",
    material="wood_prop",
    name="physics_cart",
    origin="Vanilla",
    tags=""
  },
  {
    file="data/entities/props/physics_chain_torch.xml",
    image="data/props_gfx/torch_hang_unlit.png",
    material="metal_nohit",
    name="physics_chain_torch",
    origin="Vanilla",
    tags="hittable"
  },
  {
    file="data/entities/props/physics_chain_torch_blue.xml",
    image="data/props_gfx/torch_hang_unlit.png",
    material="metal_nohit",
    name="physics_chain_torch_blue",
    origin="Vanilla",
    tags="hittable"
  },
  {
    file="data/entities/props/physics_chain_torch_ghostly.xml",
    image="data/props_gfx/torch_hang_unlit.png",
    material="metal_nohit",
    name="physics_chain_torch_ghostly",
    origin="Vanilla",
    tags="hittable"
  },
  {
    file="data/entities/props/physics_chair_1.xml",
    image="data/props_gfx/chair_1.png",
    material="wood_prop",
    name="physics_chair_1",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_chair_2.xml",
    image="data/props_gfx/chair_2.png",
    material="wood_prop",
    name="physics_chair_2",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_chandelier.xml",
    image="data/props_gfx/chandelier.png",
    material="metal_nohit",
    name="physics_chandelier",
    origin="Vanilla",
    tags="hittable"
  },
  {
    file="data/entities/props/physics_crate.xml",
    image="data/props_gfx/crate.png",
    material="wood_prop",
    name="physics_crate",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_darksun_rock.xml",
    image="data/items_gfx/normals_orb_40_noise.png",
    material="gem_box2d_darksun",
    name="physics_darksun_rock",
    origin="Vanilla",
    tags="darksunrock"
  },
  {
    file="data/entities/props/physics_electricity_source.xml",
    image="data/props_gfx/stone_01.png",
    material="rock_box2d",
    name="physics_electricity_source",
    origin="Vanilla",
    tags=""
  },
  {
    file="data/entities/props/physics_fungus.xml",
    image="data/props_gfx/physics_fungus_cap_01.png",
    material="fungus_loose",
    name="physics_fungus",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_fungus_acid.xml",
    image="data/props_gfx/physics_fungus_acid_cap_01.png",
    material="fungus_loose_green",
    name="physics_fungus_acid",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_fungus_acid_big.xml",
    image="data/props_gfx/physics_fungus_acid_cap_03.png",
    material="fungus_loose_green",
    name="physics_fungus_acid_big",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_fungus_acid_huge.xml",
    image="data/props_gfx/physics_fungus_acid_cap_04.png",
    material="fungus_loose_green",
    name="physics_fungus_acid_huge",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_fungus_acid_hugeish.xml",
    image="data/props_gfx/physics_fungus_acid_cap_04.png",
    material="fungus_loose_green",
    name="physics_fungus_acid_hugeish",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_fungus_acid_small.xml",
    image="data/props_gfx/physics_fungus_acid_cap_02.png",
    material="fungus_loose_green",
    name="physics_fungus_acid_small",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_fungus_big.xml",
    image="data/props_gfx/physics_fungus_cap_03.png",
    material="fungus_loose",
    name="physics_fungus_big",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_fungus_huge.xml",
    image="data/props_gfx/physics_fungus_cap_04.png",
    material="fungus_loose",
    name="physics_fungus_huge",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_fungus_hugeish.xml",
    image="data/props_gfx/physics_fungus_cap_04.png",
    material="fungus_loose",
    name="physics_fungus_hugeish",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_fungus_small.xml",
    image="data/props_gfx/physics_fungus_cap_02.png",
    material="fungus_loose",
    name="physics_fungus_small",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_fungus_trap.xml",
    image="data/props_gfx/physics_fungus_trap_cap_02.png",
    material="fungus_loose",
    name="physics_fungus_trap",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT,fungitrap_02"
  },
  {
    file="data/entities/props/physics_gem.xml",
    image="data/props_gfx/gem_normalmap.png",
    material="gem_box2d",
    name="physics_gem",
    origin="Vanilla",
    tags=""
  },
  {
    file="data/entities/props/physics_glass_shard_01.xml",
    image="data/props_gfx/glass_shard_01.png",
    material="glass_box2d",
    name="physics_glass_shard_01",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_glass_shard_02.xml",
    image="data/props_gfx/glass_shard_02.png",
    material="glass_box2d",
    name="physics_glass_shard_02",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_glass_shard_03.xml",
    image="data/props_gfx/glass_shard_03.png",
    material="glass_box2d",
    name="physics_glass_shard_03",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_glass_shard_04.xml",
    image="data/props_gfx/glass_shard_04.png",
    material="glass_box2d",
    name="physics_glass_shard_04",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_grass_01.xml",
    image="data/props_gfx/grass_stalk.png",
    material="fungus_loose",
    name="physics_grass_01",
    origin="Vanilla",
    tags=""
  },
  {
    file="data/entities/props/physics_grass_02.xml",
    image="data/props_gfx/grass_stalk.png",
    material="fungus_loose",
    name="physics_grass_02",
    origin="Vanilla",
    tags=""
  },
  {
    file="data/entities/props/physics_hanging_wire.xml",
    name="physics_hanging_wire",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_lantern.xml",
    image="data/props_gfx/lantern.png",
    material="glass_box2d",
    name="physics_lantern",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_lantern_small.xml",
    image="data/props_gfx/lantern_small.png",
    material="glass_box2d",
    name="physics_lantern_small",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_logo.xml",
    image="data/props_gfx/logo_eye.png",
    material="wood_loose",
    name="physics_logo",
    origin="Vanilla",
    tags="mortal"
  },
  {
    file="data/entities/props/physics_logo_1.xml",
    image="data/props_gfx/logo_1.png",
    material="wood_loose",
    name="physics_logo_1",
    origin="Vanilla",
    tags="mortal"
  },
  {
    file="data/entities/props/physics_logo_2.xml",
    image="data/props_gfx/logo_2.png",
    material="wood_loose",
    name="physics_logo_2",
    origin="Vanilla",
    tags="mortal"
  },
  {
    file="data/entities/props/physics_logo_3.xml",
    image="data/props_gfx/logo_3.png",
    material="wood_loose",
    name="physics_logo_3",
    origin="Vanilla",
    tags="mortal"
  },
  {
    file="data/entities/props/physics_minecart.xml",
    image="data/props_gfx/minecart.png",
    material="metal_rust",
    name="physics_minecart",
    origin="Vanilla",
    tags=""
  },
  {
    file="data/entities/props/physics_mining_lamp.xml",
    image="data/props_gfx/minelamp.png",
    material="wood_prop",
    name="physics_mining_lamp",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_pata.xml",
    image="data/props_gfx/pata.png",
    material="rock_box2d_hard",
    name="physics_pata",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_pressure_tank.xml",
    image="data/props_gfx/pressure_tank.png",
    material="steel",
    name="physics_pressure_tank",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_propane_tank.xml",
    image="data/props_gfx/propane_tank.png",
    material="steel",
    name="physics_propane_tank",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_sandbag.xml",
    image="data/props_gfx/sandbag.png",
    material="rock_box2d",
    name="physics_sandbag",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_seamine.xml",
    image="data/props_gfx/seamine.png",
    material="metal_rust",
    name="physics_seamine",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_skateboard.xml",
    image="data/props_gfx/skateboard.png",
    material="wood_prop",
    name="physics_skateboard",
    origin="Vanilla",
    tags=""
  },
  {
    file="data/entities/props/physics_skull_01.xml",
    image="data/props_gfx/skull_01.png",
    material="bone_box2d",
    name="physics_skull_01",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_skull_02.xml",
    image="data/props_gfx/skull_02.png",
    material="bone_box2d",
    name="physics_skull_02",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_skull_03.xml",
    image="data/props_gfx/skull_03.png",
    material="bone_box2d",
    name="physics_skull_03",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_spawners/physics_crane_tank_spawner.xml",
    name="physics_crane_tank_spawner",
    origin="Vanilla",
    tags="trailer"
  },
  {
    file="data/entities/props/physics_statue.xml",
    image="data/props_gfx/statue.png",
    material="templebrick_box2d",
    name="physics_statue",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_stone_01.xml",
    image="data/props_gfx/stone_01.png",
    material="rock_box2d",
    name="physics_stone_01",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_stone_02.xml",
    image="data/props_gfx/stone_02.png",
    material="rock_box2d",
    name="physics_stone_02",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_stone_03.xml",
    image="data/props_gfx/stone_03.png",
    material="rock_box2d",
    name="physics_stone_03",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_stone_04.xml",
    image="data/props_gfx/stone_04.png",
    material="rock_box2d",
    name="physics_stone_04",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_sun_rock.xml",
    image="data/items_gfx/normals_orb_40_noise.png",
    material="gem_box2d_yellow_sun_gravity",
    name="physics_sun_rock",
    origin="Vanilla",
    tags="sunrock"
  },
  {
    file="data/entities/props/physics_table.xml",
    image="data/props_gfx/table.png",
    material="wood_prop",
    name="physics_table",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_temple_rubble_01.xml",
    image="data/props_gfx/temple_rubble_01.png",
    material="rock_box2d",
    name="physics_temple_rubble_01",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_temple_rubble_02.xml",
    image="data/props_gfx/temple_rubble_02.png",
    material="rock_box2d",
    name="physics_temple_rubble_02",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_temple_rubble_03.xml",
    image="data/props_gfx/temple_rubble_03.png",
    material="rock_box2d",
    name="physics_temple_rubble_03",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_temple_rubble_04.xml",
    image="data/props_gfx/temple_rubble_04.png",
    material="rock_box2d",
    name="physics_temple_rubble_04",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_temple_rubble_05.xml",
    image="data/props_gfx/temple_rubble_05.png",
    material="rock_box2d",
    name="physics_temple_rubble_05",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_temple_rubble_06.xml",
    image="data/props_gfx/temple_rubble_06.png",
    material="rock_box2d",
    name="physics_temple_rubble_06",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_templedoor.xml",
    image="data/props_gfx/temple_door.png",
    material="metal_prop",
    name="physics_templedoor",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT,temple_door"
  },
  {
    file="data/entities/props/physics_templedoor2.xml",
    image="data/props_gfx/temple_door_wheel.png",
    material="metal_prop",
    name="physics_templedoor2",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT,temple_door"
  },
  {
    file="data/entities/props/physics_torch_stand.xml",
    image="data/props_gfx/torch_stand_base.png",
    material="metal_nohit",
    name="physics_torch_stand",
    origin="Vanilla",
    tags="hittable"
  },
  {
    file="data/entities/props/physics_torch_stand_blue.xml",
    image="data/props_gfx/torch_stand_base.png",
    material="metal_nohit",
    name="physics_torch_stand_blue",
    origin="Vanilla",
    tags="hittable"
  },
  {
    file="data/entities/props/physics_torch_stand_intro.xml",
    image="data/props_gfx/torch_stand_base.png",
    material="metal_nohit",
    name="physics_torch_stand_intro",
    origin="Vanilla",
    tags="hittable"
  },
  {
    file="data/entities/props/physics_trap_circle_acid.xml",
    image="data/props_gfx/trap_acid.png",
    material="steel",
    name="physics_trap_circle_acid",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_trap_electricity.xml",
    image="data/props_gfx/trap_electricity.png",
    material="steel",
    name="physics_trap_electricity",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_trap_electricity_enabled.xml",
    image="data/props_gfx/trap_electricity.png",
    material="steel",
    name="physics_trap_electricity_enabled",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_trap_ignite.xml",
    image="data/props_gfx/trap_ignite_a.png",
    material="steel",
    name="physics_trap_ignite",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_trap_ignite_enabled.xml",
    image="data/props_gfx/trap_ignite_a.png",
    material="steel",
    name="physics_trap_ignite_enabled",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_tubelamp.xml",
    image="data/props_gfx/tubelamp.png",
    material="glass_box2d",
    name="physics_tubelamp",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_vase.xml",
    image="data/props_gfx/vase.png",
    material="rock_box2d",
    name="physics_vase",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_vase_longleg.xml",
    image="data/props_gfx/vase2.png",
    material="rock_box2d",
    name="physics_vase_longleg",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_wheel.xml",
    image="data/props_gfx/wheel.png",
    material="wood_prop",
    name="physics_wheel",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_wheel_small.xml",
    image="data/props_gfx/wheel_small.png",
    material="wood_prop",
    name="physics_wheel_small",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/physics_wheel_stand_01.xml",
    image="data/props_gfx/wheel_stand_01.png",
    material="wood_player_b2",
    name="physics_wheel_stand_01",
    origin="Vanilla",
    tags=""
  },
  {
    file="data/entities/props/physics_wheel_stand_02.xml",
    image="data/props_gfx/wheel_stand_02.png",
    material="wood_player_b2",
    name="physics_wheel_stand_02",
    origin="Vanilla",
    tags=""
  },
  {
    file="data/entities/props/physics_wheel_stand_03.xml",
    image="data/props_gfx/wheel_stand_03.png",
    material="wood_player_b2",
    name="physics_wheel_stand_03",
    origin="Vanilla",
    tags=""
  },
  {
    file="data/entities/props/physics_wheel_tiny.xml",
    image="data/props_gfx/wheel_tiny.png",
    material="wood_prop",
    name="physics_wheel_tiny",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/pumpkin_01.xml",
    image="data/props_gfx/pumpkin_01.png",
    material="meat_pumpkin",
    name="pumpkin_01",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/pumpkin_02.xml",
    image="data/props_gfx/pumpkin_02.png",
    material="meat_pumpkin",
    name="pumpkin_02",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/pumpkin_03.xml",
    image="data/props_gfx/pumpkin_03.png",
    material="meat_pumpkin",
    name="pumpkin_03",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/pumpkin_04.xml",
    image="data/props_gfx/pumpkin_04.png",
    material="meat_pumpkin",
    name="pumpkin_04",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/pumpkin_05.xml",
    image="data/props_gfx/pumpkin_05.png",
    material="meat_pumpkin",
    name="pumpkin_05",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/rainforest_tree_01.xml",
    image="data/vegetation/swamp_cropped_01.png",
    material="wood_loose",
    name="rainforest_tree_01",
    origin="Vanilla",
    tags="vegetation,pixelsprite"
  },
  {
    file="data/entities/props/rainforest_tree_02.xml",
    image="data/vegetation/swamp_cropped_02.png",
    material="wood_loose",
    name="rainforest_tree_02",
    origin="Vanilla",
    tags="vegetation,pixelsprite"
  },
  {
    file="data/entities/props/rainforest_tree_03.xml",
    image="data/vegetation/swamp_cropped_03.png",
    material="wood_loose",
    name="rainforest_tree_03",
    origin="Vanilla",
    tags="vegetation,pixelsprite"
  },
  {
    file="data/entities/props/rainforest_tree_04.xml",
    image="data/vegetation/swamp_cropped_04.png",
    material="wood_loose",
    name="rainforest_tree_04",
    origin="Vanilla",
    tags="vegetation,pixelsprite"
  },
  {
    file="data/entities/props/rainforest_tree_05.xml",
    image="data/vegetation/swamp_cropped_05.png",
    material="wood_loose",
    name="rainforest_tree_05",
    origin="Vanilla",
    tags="vegetation,pixelsprite"
  },
  {
    file="data/entities/props/rainforest_tree_06.xml",
    image="data/vegetation/swamp_cropped_06.png",
    material="wood_loose",
    name="rainforest_tree_06",
    origin="Vanilla",
    tags="vegetation,pixelsprite"
  },
  {
    file="data/entities/props/sarcophagus.xml",
    image="data/props_gfx/sarcophagus.png",
    material="rock_loose",
    name="sarcophagus",
    origin="Vanilla",
    tags="prop,pixelsprite"
  },
  {
    file="data/entities/props/sarcophagus_evil.xml",
    image="data/props_gfx/sarcophagus_evil.png",
    material="rock_loose",
    name="sarcophagus_evil",
    origin="Vanilla",
    tags="mortal,prop,pixelsprite,hittable"
  },
  {
    file="data/entities/props/statue_back.xml",
    image="data/props_gfx/statue_back.png",
    material="rock_loose",
    name="statue_back",
    origin="Vanilla",
    tags="prop,pixelsprite"
  },
  {
    file="data/entities/props/statues/statue_rock_01.xml",
    image="data/props_gfx/statues/statue_rock_01.png",
    material="rock_box2d",
    name="statue_rock_01",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/statues/statue_rock_02.xml",
    image="data/props_gfx/statues/statue_rock_02.png",
    material="rock_box2d",
    name="statue_rock_02",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/statues/statue_rock_03.xml",
    image="data/props_gfx/statues/statue_rock_03.png",
    material="rock_box2d",
    name="statue_rock_03",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/statues/statue_rock_04.xml",
    image="data/props_gfx/statues/statue_rock_04.png",
    material="rock_box2d",
    name="statue_rock_04",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/statues/statue_rock_05.xml",
    image="data/props_gfx/statues/statue_rock_05.png",
    material="rock_box2d",
    name="statue_rock_05",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/statues/statue_rock_06.xml",
    image="data/props_gfx/statues/statue_rock_06.png",
    material="rock_box2d",
    name="statue_rock_06",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/statues/statue_rock_07.xml",
    image="data/props_gfx/statues/statue_rock_07.png",
    material="rock_box2d",
    name="statue_rock_07",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/statues/statue_rock_08.xml",
    image="data/props_gfx/statues/statue_rock_08.png",
    material="rock_box2d",
    name="statue_rock_08",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/statues/statue_rock_09.xml",
    image="data/props_gfx/statues/statue_rock_09.png",
    material="rock_box2d",
    name="statue_rock_09",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/statues/statue_rock_10.xml",
    image="data/props_gfx/statues/statue_rock_10.png",
    material="rock_box2d",
    name="statue_rock_10",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/statues/statue_rock_11.xml",
    image="data/props_gfx/statues/statue_rock_11.png",
    material="rock_box2d",
    name="statue_rock_11",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/statues/statue_rock_12.xml",
    image="data/props_gfx/statues/statue_rock_12.png",
    material="rock_box2d",
    name="statue_rock_12",
    origin="Vanilla",
    tags="prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/suspended_cage.xml",
    image="data/props_gfx/suspended_cage.png",
    material="metal_prop",
    name="suspended_cage",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/suspended_cage_broken.xml",
    image="data/props_gfx/suspended_cage_broken.png",
    material="metal_prop",
    name="suspended_cage_broken",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/suspended_chain.xml",
    image="data/props_gfx/suspended_chain.png",
    material="metal_prop",
    name="suspended_chain",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/suspended_container.xml",
    image="data/props_gfx/suspended_container.png",
    material="metal_prop",
    name="suspended_container",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/suspended_seamine.xml",
    image="data/props_gfx/seamine.png",
    material="metal_rust",
    name="suspended_seamine",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/suspended_tank_acid.xml",
    image="data/props_gfx/suspended_tank_acid.png",
    material="metal_prop",
    name="suspended_tank_acid",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/suspended_tank_radioactive.xml",
    image="data/props_gfx/suspended_tank_radioactive.png",
    material="metal_prop",
    name="suspended_tank_radioactive",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/temple_statue_01.xml",
    image="data/props_gfx/temple_statue_01.png",
    material="rock_box2d_hard",
    name="temple_statue_01",
    origin="Vanilla",
    tags="mortal,prop,hittable,homing_target,effectable_prop"
  },
  {
    file="data/entities/props/temple_statue_01_green.xml",
    image="data/props_gfx/temple_statue_01_green.png",
    material="rock_box2d_hard",
    name="temple_statue_01_green",
    origin="Vanilla",
    tags="mortal,prop,hittable,homing_target"
  },
  {
    file="data/entities/props/temple_statue_02.xml",
    image="data/props_gfx/temple_statue_02.png",
    material="rock_box2d_hard",
    name="temple_statue_02",
    origin="Vanilla",
    tags="mortal,prop,hittable,homing_target,effectable_prop"
  },
  {
    file="data/entities/props/vault_apparatus_01.xml",
    image="data/props_gfx/vault_apparatus_01.png",
    material="steel",
    name="vault_apparatus_01",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/vault_apparatus_02.xml",
    image="data/props_gfx/vault_apparatus_02.png",
    material="steel",
    name="vault_apparatus_02",
    origin="Vanilla",
    tags="mortal,prop,prop_physics,hittable,teleportable_NOT"
  },
  {
    file="data/entities/props/vault_machine_1.xml",
    image="data/props_gfx/vault_machine_1.png",
    material="metal_nohit",
    name="vault_machine_1",
    origin="Vanilla",
    tags="pixelsprite"
  },
  {
    file="data/entities/props/vault_machine_2.xml",
    image="data/props_gfx/vault_machine_2.png",
    material="metal_nohit",
    name="vault_machine_2",
    origin="Vanilla",
    tags="pixelsprite"
  },
  {
    file="data/entities/props/vault_machine_3.xml",
    image="data/props_gfx/vault_machine_3.png",
    material="metal_nohit",
    name="vault_machine_3",
    origin="Vanilla",
    tags="pixelsprite"
  },
  {
    file="data/entities/props/vault_machine_4.xml",
    image="data/props_gfx/vault_machine_4.png",
    material="metal_nohit",
    name="vault_machine_4",
    origin="Vanilla",
    tags="pixelsprite"
  },
  {
    file="data/entities/props/vault_machine_5.xml",
    image="data/props_gfx/vault_machine_5.png",
    material="metal_nohit",
    name="vault_machine_5",
    origin="Vanilla",
    tags="pixelsprite"
  },
  {
    file="data/entities/props/vault_machine_6.xml",
    image="data/props_gfx/vault_machine_6.png",
    material="metal_nohit",
    name="vault_machine_6",
    origin="Vanilla",
    tags="pixelsprite"
  },
  {
    file="data/entities/trailer/altar_torch_midas.xml",
    image="data/props_gfx/altar_torch_midas.png",
    material="templebrick_static",
    name="altar_torch_midas",
    origin="Vanilla",
    tags="vegetation,altar_torch"
  },
  {
    file="data/scripts/streaming_integration/entities/chest_random.xml",
    image="data/buildings_gfx/chest_random.png",
    material="wood_prop",
    name="chest_random",
    origin="Vanilla",
    tags="teleportable_NOT,item_physics,chest"
  }
}
