herd_id_values = {
    "-1",
    "ant",
    "apparition",
    "bat",
    "boss_dragon",
    "boss_limbs",
    "crawler",
    "curse",
    "eel",
    "electricity",
    "fire",
    "flower",
    "fly",
    "fungus",
    "ghost",
    "ghost_boss",
    "ghoul",
    "giant",
    "healer",
    "helpless",
    "ice",
    "mage",
    "mage_swapper",
    "nest",
    "orcs",
    "player",
    "rat",
    "robot",
    "slimes",
    "spider",
    "target",
    "trap",
    "wolf",
    "worm",
    "zombie",
}

arc_type_values = {
    "MATERIAL",
    "LIGHTNING",
}

projectile_type = {
    "PROJECTILE",
    "LIGHTNING",
    "VERLET",
    "MATERIAL_PARTICLE",
}

ragdoll_fx = {
    "NONE",
    "NORMAL",
    "BLOOD_EXPLOSION",
    "BLOOD_SPRAY",
    "FROZEN",
    "CONVERT_TO_MATERIAL",
    "CUSTOM_RAGDOLL_ENTITY",
    "DISINTEGRATED",
    "NO_RAGDOLL_FILE",
    "PLAYER_RAGDOLL_CAMERA",
}
