-- Global so mods can append to this if they want to.
unique_wand_sprites = {
    {
        tip_x = 10,
        tip_y = -0.5,
        offset_x = 1,
        offset_y = 3.5,
        sprite_file = "data/items_gfx/flute.xml",
        image_file = "data/items_gfx/flute.png",
        wiki_file = "Huilu (Wand).png",
    },
    {
        tip_x = 10,
        tip_y = -0.5,
        offset_x = 1,
        offset_y = 3.5,
        sprite_file = "data/items_gfx/kantele.xml",
        image_file = "data/items_gfx/kantele.png",
        wiki_file = "Wand kantele.png",
    },
    {
        tip_x = 6,
        tip_y = -0.5,
        offset_x = 0,
        offset_y = 0,
        sprite_file = "data/items_gfx/bomb_wand.xml",
        image_file = "data/items_gfx/bomb_wand.png",
        wiki_file = "Wand bomb wand.png",
    },
    {
        tip_x = 8,
        tip_y = 0.5,
        offset_x = 0,
        offset_y = 0,
        sprite_file = "data/items_gfx/handgun.xml",
        image_file = "data/items_gfx/handgun.png",
        wiki_file = "Wand handgun.png",
    },
    {
        tip_x = 17,
        tip_y = -0.5,
        offset_x = 0,
        offset_y = 0,
        sprite_file = "data/items_gfx/wands/custom/scepter_01.xml",
        image_file = "data/items_gfx/wands/custom/scepter_01.png",
        wiki_file = "Wand scepter 01.png",
    },
    {
        tip_x = 9,
        tip_y = -0.5,
        offset_x = 0,
        offset_y = 0,
        sprite_file = "data/entities/items/wands/experimental/experimental_wand_1_sprite.xml",
        image_file = "data/entities/items/wands/experimental/experimental_wand_1.png",
        wiki_file = "Wand experimental wand 1.png",
    },
    {
        tip_x = 12,
        tip_y = -0.5,
        offset_x = 0,
        offset_y = 0,
        sprite_file = "data/entities/items/wands/experimental/experimental_wand_2_sprite.xml",
        image_file = "data/entities/items/wands/experimental/experimental_wand_2.png",
        wiki_file = "Wand experimental wand 2.png",
    },
    {
        tip_x = 15,
        tip_y = 1,
        offset_x = 0,
        offset_y = 0,
        sprite_file = "data/items_gfx/wands/custom/actual_wand.xml",
        image_file = "data/items_gfx/wands/custom/actual_wand_honest.png",
        wiki_file = "Actual wand honest.png",
    },
    {
        tip_x = 15,
        tip_y = -0.5,
        offset_x = 0,
        offset_y = 0,
        sprite_file = "data/items_gfx/wands/custom/good_01.xml",
        image_file = "data/items_gfx/wands/custom/good_01.png",
        wiki_file = "Wand wand good 1.png",
    },
    {
        tip_x = 15,
        tip_y = -0.5,
        offset_x = 0,
        offset_y = 0,
        sprite_file = "data/items_gfx/wands/custom/good_02.xml",
        image_file = "data/items_gfx/wands/custom/good_02.png",
        wiki_file = "Wand wand good 2.png",
    },
    {
        tip_x = 15,
        tip_y = -0.5,
        offset_x = 0,
        offset_y = 0,
        sprite_file = "data/items_gfx/wands/custom/good_03.xml",
        image_file = "data/items_gfx/wands/custom/good_03.png",
        wiki_file = "Wand wand good 3.png",
    },
    {
        tip_x = 21,
        tip_y = 0,
        offset_x = 3,
        offset_y = 5,
        image_file = "data/items_gfx/wands/custom/skull_01.png",
        wiki_file = "Wand skull 01.png",
    },
    {
        tip_x = 14,
        tip_y = 0,
        offset_x = 3,
        offset_y = 3,
        image_file = "data/items_gfx/wands/custom/wood_01.png",
        wiki_file = "Wand wood 01.png",
    },
    {
        tip_x = 16,
        tip_y = 0,
        offset_x = 3,
        offset_y = 5,
        image_file = "data/items_gfx/wands/custom/plant_01.png",
        wiki_file = "Wand plant 01.png",
    },
    {
        tip_x = 22,
        tip_y = 0,
        offset_x = 3,
        offset_y = 5,
        image_file = "data/items_gfx/wands/custom/plant_02.png",
        wiki_file = "Wand plant 02.png",
    },
    {
        tip_x = 18,
        tip_y = 0,
        offset_x = 3,
        offset_y = 6.5,
        image_file = "data/items_gfx/wands/custom/vasta.png",
        wiki_file = "Wand vasta.png",
    },
    {
        tip_x = 17,
        tip_y = 0,
        offset_x = 3,
        offset_y = 6.5,
        image_file = "data/items_gfx/wands/custom/vihta.png",
        wiki_file = "Wand vihta.png",
    },
}
